### ISSUE TITLE
`java` installed `21.x-tem` instead of `-ms` by default

### ISSUE THREAD

**Issue by justinyoo** [devcontainers/features#1011]
Hi, Team.

I've found a few issues while using the `java` feature:

1. **Document discrepancy**:  According to this doc: https://github.com/devcontainers/features/blob/main/src/java/README.md, the default value of the `version` is `latest`. But `install.sh` uses `lts` as a default value. As you know `latest` and `lts` may or may not be the same as each other.
2. **Default OpenJDK version**: In the `sdk_install()` function from `install.sh`, if the requested version is `lts` (default value), it seems to be defaulted to `21.0.3-tem` regardless the distro is set to `ms` (default). I was expecting to install the latest version of Microsoft distro, which is `21.0.3-ms` for this case. I wonder if it's by design or not?

    https://github.com/devcontainers/features/blob/7953318c38a98d6bba8c8e78f7fb5bce095d7619/src/java/install.sh#L210-L211

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting the bugs, @gauravsaini04 can you help fix these? thanks!

**Comment by gauravsaini04** [comment]
Have raised as a probable solution in pr [#1021](https://github.com/devcontainers/features/pull/1021)

**Comment by gauravsaini04** [comment]
pr was merged!
