### ISSUE TITLE
SSL and checksum errors

### ISSUE THREAD

**Issue by pieterv-icloud-com** [devcontainers/features#1025]
Hi

For the past week I have not been able to install the PowerShell feature.

Just getting this or a checksum failure:

```
4.230 POWERSHELL_VERSION=7.4.3
4.804 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to objects.githubusercontent.com:443 
4.806 ERROR: Feature "PowerShell" (ghcr.io/devcontainers/features/powershell) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/powershell for help troubleshooting this error.
```

**Comment by pieterv-icloud-com** [comment]
Changing the version to `7.4.0` resolves it

**Comment by sliekens** [comment]
Yep, there is an issue installing v7.4.3 because of incorrect SHA256 sums in the release notes, related issue: https://github.com/PowerShell/PowerShell/issues/23975

You can use 7.4.2.

**Comment by timheuer** [comment]
I would close this issue as https://github.com/PowerShell/PowerShell/issues/23975 is the blocking issue here (and is updated)

**Comment by pieterv-icloud-com** [comment]
Thanks for letting me know
