### ISSUE TITLE
bash completion not working out of the box

### ISSUE THREAD

**Issue by dmytrokyrychuk** [devcontainers/features#1043]
Since the dev containers' main purpose is to provide an interactive development environment, I think that shell autocomplete should be enabled by default in dev containers. The `bash-completion` package should be included with `common-utils` feature.

The `bash-completion` package could be included conditionally, if INSTALL_ZSH is not set.

**Comment by samruddhikhandale** [comment]
Thanks for your request.

The bash-completion package provides programmable completion features for the Bash shell, which can significantly enhance your command-line experience by providing context-sensitive completions for commands, options, and arguments.

As it generally safe to install the bash-completion package on a Linux system, we can add it to the common-utils Feature.
Before adding, we should validate that the disk space is minimal
