### ISSUE TITLE
mcr.microsoft.com/devcontainers/typescript-node:0-16mcr.microsoft.com/devcontainers/typescript-node:0-16

### ISSUE THREAD

**Issue by piero1100** [devcontainers/features#1060]
mcr.microsoft.com/devcontainers/typescript-node:0-16

_Originally posted by @piero1100 in https://github.com/devcontainers/features/issues/576#issuecomment-2249231316_

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
