### ISSUE TITLE
Features: Update logic for PPA in bionic

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#1062]
> Note: I believe this fix may need to be applied to all features modified in https://github.com/devcontainers/features/pull/1016.

Most likely, yes! 
Let's see how this PR works and we could add similar fix to others.

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/features/issues/1056#issuecomment-2251572313_

**Comment by samruddhikhandale** [comment]
@prathameshzarkar9 Can you add this [code snippet](https://github.com/devcontainers/features/blob/main/src/git/install.sh#L35-L41) (if missing) to [these Features](https://github.com/search?q=repo%3Adevcontainers%2Ffeatures+Redhat+language%3AMarkdown&type=code) that support CentOs? 

Also, make sure to bump patch version for the Features in your PR.

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale 
Created PR for this https://github.com/devcontainers/features/pull/1079

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
All the review comments have been addressed. Test scenarios also modified accordingly to check the required pnpm is getting installed.
kindly review the same
