### ISSUE TITLE
[Java] Add JDK 22 support

### ISSUE THREAD

**Issue by alanondra** [devcontainers/features#1084]
JDK 22 was [released in March](https://openjdk.org/projects/jdk/22/) but the feature `ghcr.io/devcontainers/features/java:1` with `version` set to `latest` only goes up to 21.

**Comment by samruddhikhandale** [comment]
@prathameshzarkar9 Can you help take a look at this?  Thanks!

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,

Created a PR https://github.com/devcontainers/features/pull/1102

I have removed the get_jdk_distro function from install.sh as it was not being used correctly in the sequence of installing distro specific version until JDK_DISTRO is not passed as an argument with any specific value like: ms,tem etc.

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
kindly review the changes done in this PR to install the latest jdk 22
