### ISSUE TITLE
Desktop-lite: add test coverage

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#1089]
> Would it be possible to add a test that spins up a container and checks that those processes are running?
> 
> Definitely! 
> 
> @gauravsaini04 Can you follow up on adding test coverage?  

 _Originally posted by @samruddhikhandale in [#1085](https://github.com/devcontainers/features/issues/1085#issuecomment-2287167584)_

**Comment by gauravsaini04** [comment]
Hi, have added test cases for `xtigervnc` and `novnc` whether running on default ports assigned for them i.e. `5901` & `6080` respectively in the pr #[1090](https://github.com/devcontainers/features/pull/1090)

**Comment by gauravsaini04** [comment]
PR was merged

**Comment by bamurtaugh** [comment]
Going to close since the linked PR was merged!
