### ISSUE TITLE
PowerShell modules fail due to /usr/local/bin/pwsh: Permission denied

### ISSUE THREAD

**Issue by Merlus** [devcontainers/features#1091]
Image: "mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04"

During build there is an error installing modules due to permission issue, and pwsh can't be run after container build with same error:

Installing latest version for Az module
./install.sh: line 262: /usr/local/bin/pwsh: Permission denied

This can be fixed with:

sudo chmod +x $(readlink -f /usr/local/bin/pwsh)

Can this be done during build script prior to modules being installed?

**Comment by samruddhikhandale** [comment]
This should be fixed with https://github.com/devcontainers/features/pull/1050. Feel free to reopen if needed, thanks!
