### ISSUE TITLE
Update action files to use actions/checkout@v4

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#1106]
Update action files in this repo to use the updated `checkout` 

Fixes 👇 

![Image](https://github.com/user-attachments/assets/86a7deb0-6ce0-4cd6-8f36-ebba1257ce71)

**Comment by gvatsal60** [comment]
Hello @samruddhikhandale
I wanted to bring to your attention the pull request [#1110](https://github.com/devcontainers/features/pull/1110) for your review.

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/features/pull/1110
