### ISSUE TITLE
Allow to set versions of Python tools

### ISSUE THREAD

**Issue by SKairinos** [devcontainers/features#1113]
When using the official python feature, you can [specify which tools to install](https://github.com/devcontainers/features/blob/6123e41230425fc830c5e190005f91e88309efc2/src/python/devcontainer-feature.json#L30) BUT not the version of those tools. Please add the ability to set version numbers.

You use ":" as a delimiter.
```json
{
"toolsToInstall": "black:1.1.1,pipenv:2.2.2"
}
```

**Comment by koralowiec** [comment]
Hi @SKairinos 

It seems that specifying the package version is already supported. You can use `==` as the "delimiter"

For example, this `devcontainer.json` will provide you devcontainer with black and pipenv in the specified versions:

```json
{
	"name": "Debian",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/python:1": {
			"toolsToInstall": "black==24.4.2,pipenv==2024.0.1"
		}
	}
}
```

![image](https://github.com/user-attachments/assets/4011712c-7630-4298-aad2-b27ae507b4d6)

**Comment by bamurtaugh** [comment]
Thanks for the discussion! Going to close this issue as it seems like it's resolved, but please lmk if there's anything outstanding!

**Comment by pickfire** [comment]
```json
      "toolsToInstall": "uv>=0.5.6,<1.0.0"
```
This doesn't seemed to work since the `,` is used for different meaning.
