### ISSUE TITLE
Missing version tags for docker-outside-of-docker

### ISSUE THREAD

**Issue by rubensa** [devcontainers/features#1122]
Looks like last [docker-outside-of-docker](https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker) tag is [feature_docker-outside-of-docker_1.3.2](https://github.com/devcontainers/features/releases/tag/feature_docker-outside-of-docker_1.3.2) (for version [1.3.2](https://github.com/devcontainers/features/commit/65fb90b7fc8634986ab5644d00d66b983e9a50df) from January).

Following versions (1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0) have not been tagged (see: https://github.com/devcontainers/features/commits/main/src/docker-outside-of-docker/devcontainer-feature.json).

Could you, please, add tags for the missing releases (so it is easy to get the code at specific version)?  (and keep that tagging for future releases, like [this](https://github.com/devcontainers/features/pull/1121)).

**Comment by rubensa** [comment]
Looks like the same is happening for other features.

For example, last tag for [node](https://github.com/devcontainers/features/tree/main/src/node) is [feature_node_1.4.0](https://github.com/devcontainers/features/releases/tag/feature_node_1.4.0) where the last code is [1.6.0](https://github.com/devcontainers/features/blob/52c79b4963879dd941c67b583199ec7966e41ab4/src/node/devcontainer-feature.json).

**Comment by rubensa** [comment]
Looks like the tagging support was introduced in [devcontainers/action](https://github.com/devcontainers/action) version [v1.3.0](https://github.com/devcontainers/action/releases/tag/v1.3.0) but it's not working since last February so might me a bug silently introduced in version [v1.3.1](https://github.com/devcontainers/action/releases/tag/v1.3.1) released on March?

**Comment by rubensa** [comment]
Looks like automatic tagging is failing.  For example, in [last  release execution](https://github.com/devcontainers/features/actions/runs/10783166930/job/29904515850), in the log there is the message:

```bash
Adding repo tag 'feature_desktop-lite_1.2.5'...
Warning: Failed to automatically add repo tag, manually tag with:   'git tag feature_desktop-lite_1.2.5 b0667c5589bfe1b382c49392c58fe4c9433f1fde'
```

**Comment by rubensa** [comment]
The message comes from [here](https://github.com/devcontainers/action/blob/main/src/utils.ts#L79).

**Comment by rubensa** [comment]
As far as [I can see](https://github.com/devcontainers/action/commit/5e57a2c3d711bac39071e6eb193f51c5a1d2189b#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3d), the culprit might be the replacement from **jsonc-parser** to **json5** that might be, somehow, making the call with **octokit** to create the tag, to fail.

**Comment by bryanlittlefield** [comment]
Seeing the same issues on our end also. This has become more critical as our team is navigating around Issue #1017

**Comment by bamurtaugh** [comment]
Thanks all for flagging. @joshspicer would you mind taking a look, given your expertise in [devcontainers/action](https://github.com/devcontainers/action)?

**Comment by joshspicer** [comment]
> As far as [I can see](https://github.com/devcontainers/action/commit/5e57a2c3d711bac39071e6eb193f51c5a1d2189b#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3d), the culprit might be the replacement from jsonc-parser to json5 that might be, somehow, making the call with octokit to create the tag, to fail.

Hm, not clear to me why we moved away from jsonc-parser (which is used extensively within dev container tooling and is definitely tolerant of comments, per that PR's goal). 

Looks like there was just once instance of using the built-in JSON parser https://github.com/devcontainers/action/issues/210#issuecomment-1945199002, which I imagine should've been the only change 🤔

**Comment by joshspicer** [comment]
I forked the latest build of the extension and ran it against a [demo repo](https://github.com/joshspicer-org/neat-features/actions/runs/11187172084/job/31103698780#step:3:77) - tagging worked fine.  I suspect this is a configuration issue on this repo

**Comment by joshspicer** [comment]
Comparing the two runs, it appears to be a permissions issue with the GITHUB_TOKEN:

![Image](https://github.com/user-attachments/assets/120d27f3-6a01-4835-a1ba-ee7c93d9f839)
![Image](https://github.com/user-attachments/assets/4a69d93d-89ed-44f8-b0c3-7f673c6be94f)

**Comment by rubensa** [comment]
Just [checked](https://github.com/devcontainers/features/tags) and seems tags are being generated again.

 @bamurtaugh Should it be possible to add the "old" missing tags?

**Comment by bamurtaugh** [comment]
Thanks for the question @rubensa - @joshspicer it'd be awesome to get your insights!

**Comment by joshspicer** [comment]
We don't have any automated tooling for this and as it's one-off it is probably faster to update the tags manually.  Are you (and other folks reading this) interested primarily in the tags for `docker-outside-of-docker`?
