### ISSUE TITLE
Tag feature releases?

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/features#113]
@joshspicer @samruddhikhandale Should feature releases be tagged in the Git repo? I don't see how I would currently navigate from an OCI artifact to the commit it was created from. We usually use tags for that. What do you think?

**Comment by joshspicer** [comment]
We're currently releasing each feature independently by bumping the `version` in the feature's `devcontainer-feature.json`.

We could do something like `v0.0.5-ruby` when creating the release.  Would that make sense?

**Comment by chrmarti** [comment]
Make it `ruby-v0.0.5` to avoid collision with semver's pre-release/build labels. 👍

**Comment by joshspicer** [comment]
@samruddhikhandale , this could be introduced in addition to the versioning github action we discussed

**Comment by joshspicer** [comment]
I introduced this change to the CLI in order to hand GitHub action the appropriate tags that were pushed

https://github.com/devcontainers/cli/pull/305

**Comment by joshspicer** [comment]
This has been complete and rolled out for some time.  Tagging is done by the github action we publish (`devcontainers/action`)
