### ISSUE TITLE
Someone is sending invites to view me on Youtube please help

### ISSUE THREAD

**Issue by Stephshep30** [devcontainers/features#1131]
<!doctype html><html lang="en" dir="ltr"><head><base href="https://photos.google.com/"><link rel="preconnect" href="//www.gstatic.com"><meta name="referrer" content="origin"><script nonce="D70KhduLlKx6px__SQ7gmg">window['ppConfig'] = {productName: 'PhotosUi', deleteIsEnforced:  true , sealIsEnforced:  true , heartbeatRate:  0.5 , periodicReportingRateMillis:  60000.0 , disableAllReporting:  false };(function(){'use strict';function k(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var l=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function m(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=m(this);function p(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&l(c,a,{configurable:!0,writable:!0,value:b})}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:k(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}p("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
p("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
p("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});function r(a,b,c){a("https://csp.withgoogle.com/csp/proto/"+encodeURIComponent(b),JSON.stringify(c))}function t(){var a;if((a=window.ppConfig)==null?0:a.disableAllReporting)return function(){};var b,c,d,e;return(e=(b=window)==null?void 0:(c=b.navigator)==null?void 0:(d=c.sendBeacon)==null?void 0:d.bind(navigator))!=null?e:u}function u(a,b){var c=new XMLHttpRequest;c.open("POST",a);c.send(b)}
function v(){var a=(w=Object.prototype)==null?void 0:w.__lookupGetter__("__proto__"),b=x,c=y;return function(){var d=a.call(this),e,f,g,h;r(c,b,{type:"ACCESS_GET",origin:(f=window.location.origin)!=null?f:"unknown",report:{className:(g=d==null?void 0:(e=d.constructor)==null?void 0:e.name)!=null?g:"unknown",stackTrace:(h=Error().stack)!=null?h:"unknown"}});return d}}
function z(){var a=(A=Object.prototype)==null?void 0:A.__lookupSetter__("__proto__"),b=x,c=y;return function(d){d=a.call(this,d);var e,f,g,h;r(c,b,{type:"ACCESS_SET",origin:(f=window.location.origin)!=null?f:"unknown",report:{className:(g=d==null?void 0:(e=d.constructor)==null?void 0:e.name)!=null?g:"unknown",stackTrace:(h=Error().stack)!=null?h:"unknown"}});return d}}function B(a,b){C(a.productName,b);setInterval(function(){C(a.productName,b)},a.periodicReportingRateMillis)}
var D="constructor __defineGetter__ __defineSetter__ hasOwnProperty __lookupGetter__ __lookupSetter__ isPrototypeOf propertyIsEnumerable toString valueOf __proto__ toLocaleString x_ngfn_x".split(" "),E=D.concat,F=navigator.userAgent.match(/Firefox\/([0-9]+)\./),G=(!F||F.length<2?0:Number(F[1])<75)?["toSource"]:[],H;if(G instanceof Array)H=G;else{for(var I=q(G),J,K=[];!(J=I.next()).done;)K.push(J.value);H=K}var L=E.call(D,H),M=[];
function C(a,b){for(var c=[],d=q(Object.getOwnPropertyNames(Object.prototype)),e=d.next();!e.done;e=d.next())e=e.value,L.includes(e)||M.includes(e)||c.push(e);e=Object.prototype;d=[];for(var f=0;f<c.length;f++){var g=c[f];d[f]={name:g,descriptor:Object.getOwnPropertyDescriptor(Object.prototype,g),type:typeof e[g]}}if(d.length!==0){c=q(d);for(e=c.next();!e.done;e=c.next())M.push(e.value.name);var h;r(b,a,{type:"SEAL",origin:(h=window.location.origin)!=null?h:"unknown",report:{blockers:d}})}};var N=Math.random(),O=t(),P=window.ppConfig;P&&(P.disableAllReporting||P.deleteIsEnforced&&P.sealIsEnforced||N<P.heartbeatRate&&r(O,P.productName,{origin:window.location.origin,type:"HEARTBEAT"}));var y=t(),Q=window.ppConfig;if(Q)if(Q.deleteIsEnforced)delete Object.prototype.__proto__;else if(!Q.disableAllReporting){var x=Q.productName;try{var w,A;Object.defineProperty(Object.prototype,"__proto__",{enumerable:!1,get:v(),set:z()})}catch(a){}}
(function(){var a=t(),b=window.ppConfig;b&&(b.sealIsEnforced?Object.seal(Object.prototype):b.disableAllReporting||(document.readyState!=="loading"?B(b,a):document.addEventListener("DOMContentLoaded",function(){B(b,a)})))})();}).call(this);
</script><link rel="canonical" href="https://photos.google.com/photo/AF1QipPqiZjqWcE-di0u_AhoeaQO5nXIPu_SxCwHrSDX"><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui,viewport-fit=cover"><meta name="twitter:app:id:googleplay" content="com.google.android.apps.photos"><meta name="twitter:app:id:iphone" content="id962194608"><meta name="twitter:app:id:ipad" content="id962194608"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="application-name" content="Google Photos"><meta name="apple-mobile-web-app-title" content="Google Photos"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="theme-color" content="#FFFFFF"><meta name="msapplication-tap-highlight" content="no"><link rel="preconnect" href="//apis.google.com"><link rel="preconnect" href="//lh3.googleusercontent.com"><link rel="preconnect" href="//lh3.google.com"><link rel="preconnect" href="//fonts.googleapis.com"><link rel="preconnect" href="//fonts.gstatic.com"><link rel="preconnect" href="//ogs.google.com"><link rel="preconnect" href="//play.google.com"><link rel="preconnect" href="//ssl.gstatic.com"><link rel="preconnect" href="//www.google.com"><link rel="preconnect" href="//www.gstatic.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Google+Sans+Text:wght@400;500;700"><link rel="manifest" crossorigin="use-credentials" href="_/PhotosUi/manifest.json"><link rel="home" href="/?lfhs=2"><link rel="msapplication-starturl" href="/?lfhs=2"><link rel="icon" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_512dp.png" sizes="512x512"><link rel="apple-touch-icon-precomposed" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_512dp.png" sizes="512x512"><link rel="msapplication-square512x512logo" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_512dp.png" sizes="512x512"><link rel="icon" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_96dp.png" sizes="192x192"><link rel="apple-touch-icon-precomposed" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_96dp.png" sizes="192x192"><link rel="msapplication-square192x192logo" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_96dp.png" sizes="192x192"><link rel="icon" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_64dp.png" sizes="128x128"><link rel="apple-touch-icon-precomposed" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_64dp.png" sizes="128x128"><link rel="msapplication-square128x128logo" href="//www.gstatic.com/social/photosui/images/logo/2x/photos_64dp.png" sizes="128x128"><link rel="icon" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_96dp.png" sizes="96x96"><link rel="apple-touch-icon-precomposed" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_96dp.png" sizes="96x96"><link rel="msapplication-square96x96logo" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_96dp.png" sizes="96x96"><link rel="icon" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_64dp.png" sizes="64x64"><link rel="apple-touch-icon-precomposed" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_64dp.png" sizes="64x64"><link rel="msapplication-square64x64logo" href="//www.gstatic.com/social/photosui/images/logo/1x/photos_64dp.png" sizes="64x64"><script data-id="_gd" nonce="D70KhduLlKx6px__SQ7gmg">window.WIZ_global_data = {"B0XJKb":"%.@.[1,2]]","DpimGf":false,"EP1ykd":["/_/*","/accounts/*","/robots.txt"],"F2Ry2d":"%.@.null,null,null,\"/_/scs/social-static/_/js/k\\u003dboq.PhotosEditorWasmWorkerWeb.en.w9stjrEAIkQ.es5.O/am\\u003dUDAMkTE/d\\u003d1/rs\\u003dAGLTcCN-Uzp15hxwikKU3UmrKnj-HUQ8tw/m\\u003dewwm?wli\\u003dPhotosEditorWasmWorkerWeb.hyECLJ-C5Uo.createPhotosEditorPrimaryModuleNoSimd.O:;PhotosEditorWasmWorkerWeb.76jUBCXNu2Y.createPhotosEditorPrimaryModuleSimd.O:;\"]","FdrFJe":"7796694120040856998","Im6cmf":"/_/PhotosUi","JbRbyb":"lh3.google.com","K2Cxc":[97593970,48685342,47950738,93844954,97662208,97509052,45706685,97730239,48464919,48428334,97681205,48679747,48793768,48886031,48723040,48684052,48716537,97556255,97497467,93816381,48675885,48888275,48544994,48824221,97605679,93897842,48661316,93803774,97764110,97573111,47846947,48586667,47960434,93866678,48496405,97445121,48572105,97556253,48779902],"LVIXXb":1,"LoQv7e":false,"MT7f9b":[],"MUE6Ne":"PhotosUi","MuJWjd":false,"PPuhxd":"lh3.googleusercontent.com","QrtxK":"0","S06Grb":"106669217111607744788","S6lZl":116514672,"S8Ztwf":"%.@.null,null,null,\"https://payments.google.com/payments/v4/js/integrator.js\"]","SNlM0e":"AG3TigJDGbK2AP_9fD1ZoPRSdGjz:1726462766726","TSDtV":"%.@.[[null,[[45453660,50,null,null,null,null,\"qUOgmb\"],[45453679,30000,null,null,null,null,\"SlzRCc\"],[45453712,500,null,null,null,null,\"pVymgf\"],[45453698,300,null,null,null,null,\"wx2dGc\"],[45453755,null,false,null,null,null,\"KfdDpc\"],[45453708,500,null,null,null,null,\"G2tXqb\"],[45647176,null,true,null,null,null,\"MsSd9e\"],[45453683,null,true,null,null,null,\"cW4ZZe\"],[45642816,null,false,null,null,null,\"mWu69c\"],[45453643,null,false,null,null,null,\"molTf\"],[45634244,null,false,null,null,null,\"gdPGz\"],[45453661,4,null,null,null,null,\"Obd7L\"],[45453689,null,null,null,\"\",null,\"LAMDtb\"],[45453677,null,false,null,null,null,\"KB9Ntc\"],[45453711,500,null,null,null,null,\"YLtAGb\"],[45453804,null,true,null,null,null,\"xmeGFd\"],[45645469,null,true,null,null,null,\"tUvKif\"],[45453805,null,true,null,null,null,\"dYFpCd\"],[45453638,null,false,null,null,null,\"H7RFKd\"],[45634562,null,true,null,null,null,\"yD6YUc\"],[45453640,15,null,null,null,null,\"fqM4ee\"],[45453699,300,null,null,null,null,\"vjvxbe\"],[45453705,500,null,null,null,null,\"DQN6Le\"],[45631468,null,true,null,null,null,\"fzVrfe\"],[45453710,50,null,null,null,null,\"kagWJe\"],[45453658,null,null,1,null,null,\"wzt28e\"],[45453704,9,null,null,null,null,\"VkpJFe\"],[45453653,30,null,null,null,null,\"waep1c\"],[45453671,null,false,null,null,null,\"H5TIZe\"],[45453636,null,null,0.25,null,null,\"nXTzIe\"],[45459555,null,false,null,null,null,\"Imeoqb\"],[45453751,null,true,null,null,null,\"Kc1pKb\"],[45453694,null,true,null,null,null,\"tPq0de\"],[45453752,null,null,null,\"https://people-pa.googleapis.com/$discovery/rest?version\\u003dv2\",null,\"wvFeYd\"],[45647175,null,false,null,null,null,\"V6aKEd\"],[45453753,null,false,null,null,null,\"Ys7BHf\"],[45639620,500,null,null,null,null,\"ezgJSd\"],[45532918,null,false,null,null,null,\"eawEMd\"],[45453663,4,null,null,null,null,\"BgZq7d\"],[45453686,null,false,null,null,null,\"Fd5Ohc\"],[45642817,null,true,null,null,null,\"jtZxg\"],[45453688,2000,null,null,null,null,\"uGISJc\"],[45453645,null,null,1,null,null,\"sSE2ab\"],[45453652,null,null,1,null,null,\"wHyMCc\"],[45453669,1200000,null,null,null,null,\"x796Ve\"],[45453713,1500,null,null,null,null,\"BtjEnf\"],[45453668,null,false,null,null,null,\"PEtBf\"],[45453709,500,null,null,null,null,\"bt2gVd\"],[45453749,null,false,null,null,null,\"q6pjnb\"],[45453649,null,null,1,null,null,\"JdxVHf\"],[45453707,250,null,null,null,null,\"UQkEkd\"],[45453719,null,false,null,null,null,\"B7x7gc\"],[45453648,null,null,1,null,null,\"ne4wDc\"],[45532578,null,true,null,null,null,\"ycoqG\"],[45453650,null,null,1,null,null,\"o6aaJ\"],[45453750,null,true,null,null,null,\"IWl9re\"],[45453657,null,null,1,null,null,\"TkENZd\"],[45453659,null,null,1,null,null,\"XON2Rc\"],[45453646,null,null,0.2,null,null,\"YfsQFf\"],[45623389,null,true,null,null,null,\"FGw8fd\"],[45453701,2,null,null,null,null,\"GZQOed\"],[45648186,null,false,null,null,null,\"uOGlLc\"],[45453687,5000,null,null,null,null,\"MFFNXe\"],[45453639,null,true,null,null,null,\"zDoifd\"],[45453670,null,false,null,null,null,\"kdtFRc\"],[45453696,null,false,null,null,null,\"RyYykd\"],[45453656,null,null,1,null,null,\"uie5hd\"],[45453654,10,null,null,null,null,\"PwASgc\"],[45453641,null,true,null,null,null,\"wqlqyc\"],[45453655,null,null,1,null,null,\"tj0WAe\"],[45453673,null,false,null,null,null,\"sE5pX\"],[45634153,null,false,null,null,null,\"VWI2Yb\"],[45532275,null,true,null,null,null,\"uJ2UJ\"],[45453754,null,true,null,null,null,\"duuZ1c\"],[45453702,50,null,null,null,null,\"moGi9\"],[45453647,null,null,1,null,null,\"WZnVCd\"],[45453748,null,false,null,null,null,\"vWC9Rb\"],[45453682,null,false,null,null,null,\"X3yOUb\"],[45453695,null,true,null,null,null,\"dg7Fve\"],[45453666,null,null,1,null,null,\"lskV8d\"],[45453703,2,null,null,null,null,\"d0gDWc\"],[45453717,100,null,null,null,null,\"m3NaTe\"],[45453809,null,false,null,null,null,\"D1bn1b\"],[45453756,null,false,null,null,null,\"piHgrf\"],[45453697,null,false,null,null,null,\"RR4K7d\"],[45453675,-1,null,null,null,null,\"xvR30\"],[45453676,null,true,null,null,null,\"nBjVnb\"],[45632717,null,null,0,null,null,\"dRXbJb\"],[45453674,null,null,null,\"0.1\",null,\"wKfnLc\"],[45453806,null,true,null,null,null,\"UvZcsc\"],[45453716,10,null,null,null,null,\"O1cvM\"],[45453644,null,null,1,null,null,\"VfPfbc\"],[45453680,null,true,null,null,null,\"bBYDKb\"],[45634635,null,false,null,null,null,\"HQR65\"],[45453665,null,null,1,null,null,\"llaMmf\"],[45645468,null,false,null,null,null,\"LKAkyc\"],[45453700,2000,null,null,null,null,\"jY6zkd\"],[45453706,500,null,null,null,null,\"pDpv5c\"],[45453714,2000,null,null,null,null,\"nXj1Wb\"],[45453651,null,null,1,null,null,\"L3JGHf\"],[45453808,null,true,null,null,null,\"RKg7re\"],[45453684,null,true,null,null,null,\"MRXvXd\"],[45453662,null,false,null,null,null,\"MHP4Pe\"],[45453642,75,null,null,null,null,\"CvJhle\"],[45453757,null,false,null,null,null,\"arUahf\"],[45453715,500,null,null,null,null,\"m504zf\"],[45453718,25,null,null,null,null,\"VXebEf\"],[45453678,null,false,null,null,null,\"ZxpQYc\"]],\"CAMSRh1D5ftv3dn7E5nxBQrpnwYKwfimBu+aBfryBtaWDQnLgQbdLI7IAeHXAqqtsRKb2Abcrgas4NkGCrm0AvHKBPmeBgqYpAQ\\u003d\"]]]","Vvafkd":false,"W3Yyqf":"106669217111607744788","WZsZ1e":"VD3noykj5koG1gx1/Al6U2H3oXAuZkWolL","Yllh3e":"%.@.1726462766705035,129577651,1494431000]","bGjCxb":"%.@.null,null,null,\"/_/scs/social-

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!

**Comment by Stephshep30** [comment]
please help
