### ISSUE TITLE
Installting "docker in docker" and "docker outside of docker" with moby 26.1.5/26.1.4/24.0.9 on linux/amd64 fails at postinstall script

### ISSUE THREAD

**Issue by hellt** [devcontainers/features#1205]
### Description

when installing moby 26.1.5 via devcontainer feature defined like this:

```json
"features": {
        "ghcr.io/devcontainers/features/docker-outside-of-docker:1": {
            "version": "26.1.5",
            "dockerDashComposeVersion": "none"
        },
```

I get the following in the installation log

```
 [2024-11-28T17:57:04.286Z] #51 23.16 Get:2 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm/main arm64 moby-cli arm64 26.1.5-debian12u1 [15.9 MB]

[2024-11-28T17:57:13.297Z] #51 32.05 Setting up moby-cli (26.1.5-debian12u1) ...
  #51 32.06 Error while loading /var/lib/dpkg/info/moby-cli.postinst: Exec format error
  #51 32.06 dpkg: error processing package moby-cli (--configure):
  #51 32.06  installed moby-cli package post-installation script subprocess returned error exit status 1
```

Is this is a MSFT packaging problem?

**Comment by hellt** [comment]
tested 26.1.5, 26.1.4 and 24.0.9.
All fail when running in gh actions with linux/amd64 emulated platform

**Comment by hellt** [comment]
The root cause seems to be in the incompatible (?) postinstall script that does not handle the `--configure` argument.

More details here https://github.com/moby/moby/issues/48987#issuecomment-2507267417

**Comment by bamurtaugh** [comment]
Thanks for opening this and providing all the great insights.

I think this would be covered by https://github.com/devcontainers/features/issues/1206, so closing in favor of that issue. If these are separate though, please just let me know, and I'm more than happy to reopen.

**Comment by hellt** [comment]
Oh, sorry. This was resolved in the meantime... I had no qemu setup step in my CI pipeline, so the emulation was not there. After adding it -- installation got through
