### ISSUE TITLE
[AWS CLI] Have an option to not include the AWS Toolkit extension.

### ISSUE THREAD

**Issue by jifalops** [devcontainers/features#1228]
The AWS toolkit extension adds about 2.5 seconds to startup and I don't use it. 

I've uninstalled it countless times.

I'm using an image from Dockerhub that I built with the devcontainer CLI but it still picks up the extension when in a devcontainer. That is awesome but it made it hard to figure out why it kept getting installed.

**Comment by skyfenton** [comment]
It would be nice if this was more "opt-in" than "opt-out", but vscode does let you specify extensions you want to opt out of in your devcontainer config by prefixing its name with "-". 

Ex.

```json
"customizations": {
	"vscode": {
		"extensions": [
			"-AmazonWebServices.aws-toolkit-vscode",
		]
	}
}
```

**Comment by jifalops** [comment]
Thats actually really nice.
