### ISSUE TITLE
github-cli : Fails with signature invalid error

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#132]
`github-cli` Feature fails to install with the following error. 

![image](https://user-images.githubusercontent.com/24955913/188232539-e97a8d34-e06f-471c-8c57-e1bff037139e.png)

This error is due to the GPG key used to sign debian packages is expired. Upstream issue --> https://github.com/cli/cli/issues/6175 

Once the upstream GPG key is updated, it also needs to be modfied in this `github-cli` Feature.

**Comment by samruddhikhandale** [comment]
Fixed with https://github.com/devcontainers/features/pull/133

**Comment by jkeech** [comment]
Closing as fixed by #133
