### ISSUE TITLE
Go feature does not add `$GOPATH/bin` to the `PATH`

### ISSUE THREAD

**Issue by davidwallacejackson** [devcontainers/features#159]
Repro: https://github.com/davidwallacejackson/go-path-repro

I think this issue happens because `$GOROOT/bin` has already been added to `PATH` somehow before [these injected rc lines](https://github.com/devcontainers/features/blob/main/src/go/install.sh#L236) are run. Because the default `GOROOT` is /usr/local/go`, the path to its `bin` directory is `/usr/local/go/bin`, which contains `/go/bin` -- which then causes the match `*"\${GOPATH}/bin"*` to pass erroneously (since `/go/bin` can be found in the `PATH` string). This might be fixable just by using a regex for the match instead.

This is another example of something that would be solved by https://github.com/devcontainers/features/issues/155

**Comment by samruddhikhandale** [comment]
Fixed the issue with https://github.com/devcontainers/features/pull/162

@davidwallacejackson if you could rebuild the container (without cache), you could see the `PATH` issue resolved. 
I tested with https://github.com/davidwallacejackson/go-path-repro and the fix worked fine. 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/24955913/190791300-985bf915-ae45-4a37-a74f-40878002ab28.png">
