### ISSUE TITLE
C Sharp extension required by common utils

### ISSUE THREAD

**Issue by cailloumajor** [devcontainers/features#169]
Hello,

I wonder why C# extension requirement exists in common utilities feature?

https://github.com/devcontainers/features/blob/0258e7e66a2df165ad98f6e4c6f93b1a34cbb8f5/src/common-utils/devcontainer-feature.json#L58-L64

**Comment by samruddhikhandale** [comment]
@joshspicer any particular reason behind adding this extension to `common-utils` Feature during migration?

**Comment by jkeech** [comment]
@cailloumajor thanks for reporting! This looks like an oversight/mistake to me. It should not be included.

**Comment by samruddhikhandale** [comment]
This PR https://github.com/devcontainers/features/pull/173 cleans it up.

**Comment by samruddhikhandale** [comment]
Closing as removed the unwanted extension with https://github.com/devcontainers/features/pull/173
