### ISSUE TITLE
When git-lfs features is used, local .gitconfig wont be copied in to devcontainer

### ISSUE THREAD

**Issue by secret104278** [devcontainers/features#184]
By default, user local `.gitconfig` should be copied into devcontainer, it works when using `git` feature only.
However, when `git-lfs` is used, then it wont be copied.
I guess it probably because we run `git-lfs install` in install process, so `.gitconfig` is not empty so vscode server stop copying local `.gitconfig` to prevent from overriding.

**Comment by johnbullnz** [comment]
I'm having the same problem. `.gitconfig` seems to get copied across in the *start* phase, whereas I think the git-lfs feature is run in the *create* phase. A workaround is to just install git-lfs in the *postStartCommand* using a custom script, i.e. after `.gitconfig` is copied across to the container. Adding some control to `devcontainer.json` around exactly when `.gitconfig` gets copied would be a solution.

**Comment by johnnyreilly** [comment]
I don't know if this is definitely related, but I'm getting some odd file system permission issues with features. I'm finding that I often have to do some `chmod` shenanigans before I can `git commit` successfully

**Comment by dremsol** [comment]
Experiencing the same issue.

**Comment by samruddhikhandale** [comment]
Hi 👋 

The cause of this bug is not due to the Features, because remote containers help with the gitconfig.
I have reported this bug in https://github.com/microsoft/vscode-remote-release/issues/7589

Feel free to comment on that issue with comments/thoughts.
