### ISSUE TITLE
JAVA_HOME is set even when the feature is set to none

### ISSUE THREAD

**Issue by etienne-chrp** [devcontainers/features#188]
When trying to setup a new container for Java/Gradle you get the following error: `ERROR: JAVA_HOME is set to an invalid directory: /usr/local/sdkman/candidates/java/current`

Steps to reproduce:
1. Open empty directory in vscode
2. Reopen in container
3. Chose Java definition 
   - Version 11
   - NodeJS => none
   - Install Gradle
4. Run gradle in shell

The problem seems to be the JAVA_HOME that is being set even though we are not installing Java via the feature: 
- https://github.com/devcontainers/features/blob/main/src/java/devcontainer-feature.json#L55
- https://github.com/devcontainers/images/blob/main/src/java/.devcontainer/devcontainer.json#L8

It is overriding the value set in the container definition: https://github.com/devcontainers/images/blob/main/src/java/.devcontainer/devcontainer.json#L13

vscode: 1.71.2
devcontainer extension: v0.251.0

**Comment by kf6kjg** [comment]
Arguing with this issue too. Since I'm starting my Dockerfile with

```Dockerfile
ARG VARIANT=11-bullseye
FROM mcr.microsoft.com/devcontainers/java:0-${VARIANT}
```

I don't see a need to install another version of Java with this feature, I just want Gradle.

I added the following to the end of my Dockerfile as a workaround:

```Dockerfile
ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-current
```

**Comment by etienne-chrp** [comment]
I see that a similar issue has been raised in the `images` repository: https://github.com/devcontainers/images/issues/158

Which one should stay open?

**Comment by samruddhikhandale** [comment]
Duplicate: https://github.com/devcontainers/images/issues/158

Added thoughts - https://github.com/devcontainers/images/issues/158#issuecomment-1284652886
