### ISSUE TITLE
`NVM_VERSION` hard-coded to `0.38.0` on the node feature

### ISSUE THREAD

**Issue by justinyoo** [devcontainers/features#190]
Hi, Team.

When I look at the `install.sh` file, the `NVM_VERSION` value is hard-coded to `0.38.0`

https://github.com/devcontainers/features/blob/82960fd16b04fb4003a8765b2381bd23553737b5/src/node/install.sh#L21

Do we have a reason to pin that specific version instead of getting the latest one (`0.39.1` as of today)?

If there's no harm, can I send a PR to get the latest version of the NVM?

**Comment by johnnyreilly** [comment]
This feels like a good idea (I have no authority on this BTW 😅)

**Comment by joshspicer** [comment]
Agreed, thanks for pointing that out.  I suspect this was originally pinned for a reason, but I don't recall why (and likely it's fine to pick up the latest).  Feel free to send the PR :)

**Comment by Chuxel** [comment]
There are a few other bugs I ran into so I bumped the nvm version (since 0.38.0 has issues), and added the ability to pick a nvm version into PR #241

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/features/pull/241
