### ISSUE TITLE
Remove apt lists (`/var/lib/apt/lists/*`) the end of each scripts?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/features#191]
Previously, a mechanism was implemented in each script to reduce the number of `apt-get update`, so that only one `apt-get update` was needed to install multiple features.
However, that mechanism has now been removed, so it may make more sense to remove the cache by `rm -rf /var/lib/apt/lists/*` at the end of each script to reduce the layer size.
(especially if you pre-build and register the image in the registry)

**Comment by joshspicer** [comment]
Yes, I agree! That is something that was lost when moving over from the vscode-dev-containers repo.
