### ISSUE TITLE
update Features with appropriate `installsAfter` properties

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/features#195]
Update features to include an [installsAfter](https://containers.dev/implementors/features/#installsAfter) property where applicable.  Notably, to install after `common-utils`

**Comment by joshspicer** [comment]
should wait for https://github.com/devcontainers/cli/issues/163 to be resolved.

**Comment by johnnyreilly** [comment]
Is this related to https://github.com/devcontainers/features/issues/192

**Comment by joshspicer** [comment]
Yea in a way @johnnyreilly - This issue really represents adding `installsAfter: common-utils` to mot of the Features in this repo, since common-utils is really designed to be installed earlier on in the build. (I quite liked this comment describing why we are trying to avoid Features having a strict dependency - https://github.com/devcontainers/spec/issues/109#issuecomment-1273868565)

The concept of "Composite Features" that @chxuel was describing is unimplemented, and is a much firmer dependency.  `installsAfter` is a hint but we don't _require_ that the target Features of `installsAfter` be present.
