### ISSUE TITLE
`seccomp=profile.json` path isn't relative 

### ISSUE THREAD

**Issue by snebjorn** [devcontainers/features#207]
How is a path to a seccomp profile file specificed?

The doesn't work when **seccomp.json** is in same folder as **devcontainer-feature.json**
```json
{
  "securityOpt": ["seccomp=seccomp.json"]
}
```

seccomp accepts a path https://docs.docker.com/engine/security/seccomp/

```
$ docker run --rm \
             -it \
             --security-opt seccomp=/path/to/seccomp/profile.json \
             hello-world
```

**Comment by eitsupi** [comment]
Perhaps you have the wrong repository to create the issue?
That sounds like an https://github.com/devcontainers/cli problem.

**Comment by snebjorn** [comment]
you're probably right. Reposting there :)
