### ISSUE TITLE
devcontainer.json stop functioning properly after last VSCode update

### ISSUE THREAD

**Issue by aborealis** [devcontainers/features#208]
Some directives from devcontainer.json ceased to execute. They worked fine before the last VSCode update.

1. Extensions are not installed (though they are listed)
```json
"customizations": {
	"vscode": {
		"extensions": [
			"burkeholland.simple-react-snippets",
			"esbenp.prettier-vscode",
			"dbaeumer.vscode-eslint",
			"NuclleaR.vscode-extension-auto-import"
		]
	}
}
```
2. Shutdown actions and post create commands are also ignored:
```json
"shutdownAction": "none",
"postCreateCommand": "python -m pip install -U pytest pytest-django autopep8"
```

VSCode Vesrion - 1.72.0
OS where the issue happens
- Kali Linux
- MacOs
(Both OS are updated)

**Comment by eitsupi** [comment]
Perhaps you are submitting to the wrong repository.

I recommend checking this repository.
https://github.com/microsoft/vscode-remote-release

**Comment by aborealis** [comment]
Ok, I will duplicate it there. Thanks for poining.
