### ISSUE TITLE
Take advantage of new ${devcontainerId} property in docker-in-docker script

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/features#248]
The latest CLI is needed, so as the current iteration testing push rounds out, we can add this to the docker-in-docker script.

HOWEVER, this would be a breaking change for existing volumes, so I'd suggest we do a major version bump for the docker-in-docker script when this gets released.

**Comment by fred-asimov** [comment]
This is great news! Already up and running with it...

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/features/pull/314
