### ISSUE TITLE
pnpm

### ISSUE THREAD

**Issue by mrhappyma** [devcontainers/features#256]
I think [pnpm](https://pnpm.io) would be a good addition :)

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the suggestion. Unfortunately, this repository will accept improvement and bug fix contributions related to the
[current set of maintained Features](https://github.com/devcontainers/features/tree/main/src).

We would appreciate are willing to create a new Feature in a repository you control and share it with the community. We have a starter repo [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) which should help you with self authoring Feature.

**Comment by mrhappyma** [comment]
Alright, Thanks for letting me know!

**Comment by NicoVIII** [comment]
I wrote my first, simple feature, which simply installs pnpm via npm.
Alternatively you can install it via `postCreateCommand` Option, but if you prefer to have it as a feature, you could try this one out :)
https://github.com/NicoVIII/devcontainer-features/tree/main/src/pnpm

**Comment by samruddhikhandale** [comment]
@NicoVIII This is awesome 👏  

If you'd like to share this Feature with the community, we'd appreciate adding this to the [public index](https://containers.dev/features). Refer to instructions [here](https://github.com/devcontainers/feature-starter#adding-features-to-the-index)
