### ISSUE TITLE
[JAVA] Install a specific version of Gradle or Maven

### ISSUE THREAD

**Issue by etienne-chrp** [devcontainers/features#260]
In the previous Java image, it was possible ton install a specific version of Gradle or Maven: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/java#installing-maven-or-gradle

As the new docker image is based on the Java feature to [install ](https://github.com/devcontainers/images/tree/main/src/java#installing-maven-or-gradle) them, it would be nice for continuity to provide the possibility to choose a specific version.

**Comment by samruddhikhandale** [comment]
Hi 👋 

@etienne-chrp It is a wonderful suggestion and makes sense. Would you be interested in contributing and opening up a PR for the [Java Feature](https://github.com/devcontainers/features/tree/main/src/java) with the change?

// cc @joshspicer
