### ISSUE TITLE
Enhancement: az cli should mount the hosts .azure folder into the devcontainer

### ISSUE THREAD

**Issue by ross-p-smith** [devcontainers/features#265]
When installing the az cli feature, it would be excellent if it also mounted the host .azure folder into the devcontainer so that your azure session was persisted.

```
"mounts": [
// Mounts the login details from the host machine so azcli works in the container
"type=bind,source=${env:HOME}${env:USERPROFILE}/.azure,target=/home/vscode/.azure",
]
```

**Comment by joshspicer** [comment]
This sounds like a great use-case for the current spec proposal here https://github.com/devcontainers/spec/issues/132

I imagine that some people may not want this behavior, nor do we want container creations to fail if there isn't such a directory. That said, super useful if you already have config locally 👍

**Comment by joshspicer** [comment]
Actually looking closer, it's the same example that @stuartleeks has :)

**Comment by stuartleeks** [comment]
@ross-p-smith I know it's not _quite_ what you asked for, but I've created the `azure-cli-persistence` feature ([here](https://github.com/stuartleeks/dev-container-features/blob/main/src/azure-cli-persistence/README.md)) which auto-attaches a volume and symlinks the `~/.azure` folder in the container to it. Whilst this isn't sharing the host's `.azure` folder, it does mean that the logins are preserved across dev container rebuilds etc.

I've started migrating to this approach as it allows me to have different logins across host and various dev containers :-)

**Comment by ross-p-smith** [comment]
I'll give it a whirl - this might actually be better than what I was looking for anyway! Thanks Stuart
