### ISSUE TITLE
install/start a daemon in a feature

### ISSUE THREAD

**Issue by cnuss** [devcontainers/features#273]
greetings!

I was wondering if it'd be possible to set up a daemon within a feature install?

as a basic example, I could install Cron within a feature, but something would need to call `service cron start` once the devcontainer is launched, and currently the only ways I can think of:

 - expect the user to have to add a postStartCommand along with the feature -- this seems fragile as the user would have to remember to add it
 - add a script to /etc/profile.d to start the daemon -- this seems fragile since the daemon won't start until a terminal is first established, and might have to check if the process is already running 

similar to what I need, I've found that a ssh daemon is automatically running, is it possible to hook into what starts that daemon, or are there any other possible mechanisms for this?

thank you!

**Comment by jkeech** [comment]
One way to do this is to have the feature provide an `entrypoint` in `devcontainer-feature.json` (reference: https://containers.dev/implementors/features/#devcontainer-feature-json-properties). The entrypoint script runs on container startup and could start your daemon/service there.

**Comment by cnuss** [comment]
I will take a look at that thank you!

**Comment by jkeech** [comment]
>similar to what I need, I've found that a ssh daemon is automatically running, is it possible to hook into what starts that daemon, or are there any other possible mechanisms for this?

The entrypoint is indeed what the `sshd` feature uses 😄. Here's the link for that so you can see how it's implemented: https://github.com/devcontainers/features/blob/3020d6da64798ee994d407ffd3ce3f800f6dff92/src/sshd/devcontainer-feature.json#L17

**Comment by joshspicer** [comment]
I agree with @jkeech that is the recommended way to do what you're asking.  Please feel free to re-open if this isn't helpful for your use case, or if you have any questions :)

**Comment by cnuss** [comment]
Closing the loop! This worked like a charm!

For anyone that stumbles along this thread, here's what I did to get `cron` working in a container:

`cron-init.sh` (in feature folder next to `install.sh`, bits were borrowed from `/usr/local/share/ssh-init.sh`):
```
#!/usr/bin/env bash
set -e 

sudoIf()
{
    if [ "$(id -u)" -ne 0 ]; then
        sudo "$@"
    else
        "$@"
    fi
}

sudoIf /etc/init.d/cron start 2>&1 | sudoIf tee /tmp/cron.log > /dev/null

set +e
exec "$@"
```

`install.sh`:
```
apt-get update
apt-get -y install --no-install-recommends cron
rm -rf /var/lib/apt/lists/*

cp cron-init.sh /usr/local/share/cron-init.sh
chmod +rx /usr/local/share/cron-init.sh
```

`devcontainer-feature.json`:
```
{
  "name": "...",
  "id": "...",
  "version": "0.1.6",
  "description": "Assume an AWS role using SAML.to",
  "options": {
     ...
  },
  "entrypoint": "/usr/local/share/cron-init.sh"
}
```
