### ISSUE TITLE
How to add gcloud components

### ISSUE THREAD

**Issue by st-little** [devcontainers/features#278]
I installed gcloud by adding "ghcr.io/dhoeric/features/google-cloud-cli:1" to features.

```json
	"features": {
		"ghcr.io/dhoeric/features/google-cloud-cli:1": {
			"version": "409.0.0"
		}
	},
```

Is there any way to add more [components](https://cloud.google.com/sdk/docs/components#additional_components)?

**Comment by Chuxel** [comment]
Hey @st-little - This is not something maintained here.  Please raise the question with the feature author at https://github.com/dhoeric/features. Thanks for the interest tho!!
