### ISSUE TITLE
docker-in-docker fails locally on linux (works in codespaces)

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/features#285]
Migrated from https://github.com/microsoft/vscode-dev-containers/issues/1687

From @dsyer

----

I have a fairly vanilla Ubuntu host which runs docker happily. When I start a devcontainer locally with docker-in-docker it fails. JSON:

```json
{
	"name": "hello",
	"image": "mcr.microsoft.com/devcontainers/base:ubuntu",
	"remoteUser": "vscode",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:1": {}
	}
}
```

Error:

```
$ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

The same JSON works in codespaces:

```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by Chuxel** [comment]
How was Docker installed?  Is this Docker Desktop for Linux, an [official docker install](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) via their apt repo?  Something else?  

Re: rootless, this is what I am referring to https://docs.docker.com/engine/security/rootless

**Comment by dsyer** [comment]
I remember rootless now. I did try it out once and it couldn’t support some of the things I do so I ditched it. I’m on a pretty vanilla Ubuntu (20.04) with docker installed from the Ubuntu package manager. It usually works, and I have definitely used docker in devcontainers before this. So something may have changed, or this new “feature” isn’t the same way I installed it before.

**Comment by Chuxel** [comment]
🤔 The same script was used as a base. Hmmm. You can try using `ghcr.io/devcontainers/features/docker-in-docker:1.0.4` which is before some recent updates to support different DNS options in the event that caused a problem.

**Comment by edouard-lopez** [comment]
I have the same issue after forking the https://github.com/devcontainers/feature-starter/tree/c23b8feef8bcb54a8d783043b9269d34f5172b1e.

## Context

### OS
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

### Docker
```
❯ docker version 
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:14 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:01 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### VSCode

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.0-23-generic
Sandboxed: No
```

**Comment by dsyer** [comment]
I changed the host and container to Ubuntu jammy (22.04) and it seems to work that way (when the timeout in https://github.com/devcontainers/cli/issues/281 doesn't happen, which makes it hard to test).

**Comment by edouard-lopez** [comment]
Thanks, @dsyer, for the update.
For me, it happens on my desktop machine, downgrading the OS is not really an option.

**Comment by samruddhikhandale** [comment]
Chatted with @edouard-lopez, the issue he is facing looks like a remote containers one to me. Created an issue with details - https://github.com/microsoft/vscode-remote-release/issues/7605

**Comment by Chuxel** [comment]
Yeah, as discussed, this could be due to two dev containers attempting to use Docker-in-Docker due to https://github.com/devcontainers/features/issues/248 not being done yet.

If you want to see if this resolves the issue in the mean time, I patched and published an update elsewhere with the fix.

```
"ghcr.io/chuxel/feature-library/dind-patched:2": {}
```

**Comment by dsyer** [comment]
That works, thanks. So it was nothing to do with the jammy upgrade probably (jammy still broken for me with the official docker-in-docker feature).

**Comment by samruddhikhandale** [comment]
https://github.com/devcontainers/features/issues/248 is closed as fixed with https://github.com/devcontainers/features/pull/314

Update is released to the `docker-in-docker` Feature which fixes failures on a local machine. 🚀 

Feel free to re-open if the bug resurfaces, thanks! 😄

**Comment by kamal2311** [comment]
@samruddhikhandale can this be please fixed in docker-outside-of-docker also?
This issue still exists there.

**Comment by samruddhikhandale** [comment]
@kamal2311 We don't volume mount in case of `docker-outside-of-docker`, see https://github.com/devcontainers/features/blob/main/src/docker-outside-of-docker/devcontainer-feature.json#L47-L53. Hence, I don't expect ^ it to cause any issues. 

Docker-outside-of-docker is a different model, where the host’s docker socket is bind mounted into the container, so docker commands executed from inside the container actually execute on the host. I wonder if you are facing trouble with Docker on your host machine, feel free to open a new issue if required.
