### ISSUE TITLE
Node feature permissions incorrect with custom non-root user

### ISSUE THREAD

**Issue by benjaminwood** [devcontainers/features#307]
When the container is running with a non-root user, does not have a UID of `1000`, and is not named `vscode`, `node`, or `codespace`, the install script fails to set correct permissions on the node installation.

For example, say you're using Docker for mac and the container is running a user called `app` with a UID of `501`. The node installation will proceed as root, which results in a dev container with a broken node installation (for the `app` user).

The code in question is seen here:

https://github.com/devcontainers/features/blob/188f1ef26bc8fa942d552dfaa8596091a8a39126/src/node/install.sh#L38-L52

A workaround is to set `username` in the feature options, which is undocumented:

```json
"features": {
  "ghcr.io/devcontainers/features/node:1": {
    "version": "18",
    "username": "app"
  }
}
```

There is a `_DEV_CONTAINERS_IMAGE_USER` build arg passed to Dockerfile-with-features. If this build arg could be set as an environment variable when the feature install.sh is run, it could be used to determine the correct user without the "automatic" behavior that is currently used. This approach would require some changes outside of the install script itself (devcontainer cli?).

**Comment by jkeech** [comment]
Thanks for reporting! I think we just need to update the install script to leverage the new `_REMOTE_USER` and `_CONTAINER_USER` variables which get passed in automatically. Reference: https://github.com/devcontainers/spec/blob/main/proposals/features-user-env-variables.md

cc @samruddhikhandale

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/features/pull/264

@benjaminwood feel free to re-open if you find any other issues! 😄
