### ISSUE TITLE
Python feature does not make python available in devcontainer base images

### ISSUE THREAD

**Issue by vinicius507** [devcontainers/features#316]
Using python feature with devcontainer `base-ubuntu` image does not provide Python for Dockerfile build steps.

### Expected behaviour
Executing `RUN` clauses with python executable should run fine.

### What's happening
Executing `RUN` clauses with python executable throw an error.

### Context

- Docker version:  `Docker version 20.10.21, build baeda1f82a`
- Devcontainer Extension version: `v0.265.0`

<details>
<summary>Dockerfile</summary>

```Dockerfile
FROM mcr.microsoft.com/devcontainers/base:ubuntu-20.04

ENV PATH="/usr/local/python/current/bin:$PATH"

RUN apt update \
    && apt install -y bear clang-12 valgrind \
    && python -m pip install --upgrade pip \
    && python -m pip install norminette pre-commit
```
</details>

<details>
<summary>devcontainer.json</summary>

```json
{
  "name": "42 C Project",
  "build": {
    "dockerfile": "Dockerfile",
    "context": "."
  },
  "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
  "postCreateCommand": "bear -- make && make fclean",
  "features": {
    "ghcr.io/devcontainers/features/python:1": {}
  },
  "customizations": {
    "vscode": {
      "extensions": ["kube.42header", "vscode.cpptools"]
    }
  }
}
```
</details>

Logs: [remoteContainers-2022-11-30T01-07-53.161Z.log](https://github.com/devcontainers/features/files/10118470/remoteContainers-2022-11-30T01-07-53.161Z.log)

**Comment by vinicius507** [comment]
It seems I was misunderstanding when features `install.sh` script are run.

Now that I've read the logs carefully, I've noticed that features setup are executed post `Dockerfile` build.

Closing.

**Comment by aioue** [comment]
I'm new to devcontainers and was pulling my hair out for hours about this - the devcontainer json or the docs should make this much more clear. Features are applied **after** the Dockerfile build.
