### ISSUE TITLE
kubectl-helm-minicube: Adds retry logic to find git tags 

### ISSUE THREAD

**Issue by xec-abailey** [devcontainers/features#334]
Hello!

Have been using the kubectl devcontainer feature for about a year (or close to it) with no issues to speak of until this week. Here is the error showing up in the build log:

```
 #19 7.806 HELM_GPG_KEYS_URI=https://raw.githubusercontent.com/helm/helm/main/KEYS
2022-12-14 16:56:03.273Z: #19 7.809 GPG_KEY_SERVERS=keyserver hkp://keyserver.ubuntu.com:80
2022-12-14 16:56:03.273Z: #19 7.809 keyserver hkps://keys.openpgp.org
2022-12-14 16:56:03.274Z: #19 7.809 keyserver hkp://keyserver.pgp.com
2022-12-14 16:56:03.274Z: #19 8.012 Verification failed!
2022-12-14 16:56:03.274Z: #19 8.013 gpg: no valid OpenPGP data found.
2022-12-14 16:56:03.274Z: #19 8.013 gpg: the signature could not be verified.
```

And here is the devcontainer.json we are using: 

```json
{
	"name": "Machine Learning",
	"build": {
		"dockerfile": "../Dockerfile",
		"context": "..",
		"target": "development"
	},
	"hostRequirements": {
		"cpus": 4,
		"memory": "8gb",
		"storage": "32gb"
	},
	"runArgs": [
		"--env-file",
		".env"
	],
	"mounts": [
		"source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind",
		"source=projectname-bashhistory,target=/commandhistory,type=volume"
	],
	"initializeCommand": "docker login -u azureml-dev -p /******  ********",
	"postAttachCommand": "chmod +x scripts/build_and_push_dagster.sh",
	"extensions": [
		"ms-python.python",
		"ms-azuretools.vscode-docker",
		"ms-vscode.azure-account",
		"ms-kubernetes-tools.vscode-kubernetes-tools",
		"ms-kubernetes-tools.vscode-aks-tools",
		"eamodio.gitlens",
		"xyz.local-history",
		"ms-toolsai.jupyter",
		"gruntfuggly.todo-tree",
		"randomfractalsinc.vscode-data-preview",
		"wmaurer.change-case",
		"moshfeu.compare-folders",
		"github.copilot",
		"mutantdino.resourcemonitor",
		"tyriar.sort-lines",
		"redhat.vscode-yaml",
		"bungcip.better-toml",
		"elagil.pre-commit-helper",
		"RandomFractalsInc.vscode-vega-viewer"
	],
	"features": {
		"ghcr.io/devcontainers/features/docker-from-docker:1": {
			"version": "latest"
		},
		"ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
			"version": "latest"
		},
		"ghcr.io/devcontainers/features/azure-cli:1": {
			"version": "latest"
		},
		"ghcr.io/devcontainers/features/powershell:1": {
			"version": "latest"
		}
	},
	"containerEnv": {
		"KRB5_CONFIG": "${containerWorkspaceFolder}/.devcontainer/krb5.conf",
		"WORKSPACE_PATH": "${containerWorkspaceFolder}/",
		"DAGSTER_HOME": "${containerWorkspaceFolder}/.dagster_home",
		"PROMPT_COMMAND": "history -a",
		"HISTFILE": "/commandhistory/.bash_history"
	}
}
```

Removing the kubectl-helm-minicube feature succeeds build. Any guidance is helpful.

Thanks!

**Comment by bpkroth** [comment]
Took a brief look at the script.  Looks like it tries to infer the release from the git tags, but the Helm repo so far has only done the tag and not the release packages.

However, I think if you export `HELM=3.10.2` in your `.devcontainer/.env` (and configure your `devcontainer.json` to use that), then you should be able to (temporarily) pin the previous version in the feature script.

**Comment by bpkroth** [comment]
A proper fix in this repo would probably be to fix that `install.sh` script up to fallback to the previous version if not all the requisite files can be found.

**Comment by samruddhikhandale** [comment]
Thanks @bpkroth for suggesting a temporary fix. ✨ 

> A proper fix in this repo would probably be to fix that install.sh script up to fallback to the previous version if not all the requisite files can be found.

I agree, adding to the backlog. Will pick up soon.

**Comment by xec-abailey** [comment]
> ```js
> "ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
> 			"version": "1.25.4",
> 			"helm": "3.10.2",	// FIXME: pinning helm version. See: https://github.com/devcontainers/features/issues/334
> 			"minikube": "none"
> 		},
> ```

Confirmed this worked great, thanks!

**Comment by jnewland** [comment]
I'm encountering this failure again today as Helm is in the process of performing a release.

**Comment by gauravsaini04** [comment]
Raised PR #[875](https://github.com/devcontainers/features/pull/875)
