### ISSUE TITLE
common-utils:2 ending rc files without a trailing newline

### ISSUE THREAD

**Issue by Clockwork-Muse** [devcontainers/features#341]
With the common-utils:2 feature being released, the various rc files (`~/.bashrc`, `/etc/bash.bashrc`, `/etc/zsh/zshrc`) _no longer end with a trailing newline_.

This silently breaks every successive feature that doesn't version the dependency on common-utils (ie, pretty much all of them) and uses/copies the `updaterc` function for appending to the files.

**Comment by eitsupi** [comment]
It should be fixed by #342
