### ISSUE TITLE
[common-utils] Update meta.env file's path and format

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/features#345]
I am looking to implement the `devcontainer-info` command in our build of Dev Container images.

https://github.com/devcontainers/features/blob/2af02c198adabacff30c400b0bfcad972ce5abcc/src/common-utils/bin/devcontainer-info#L2

- Could it also support the new path like `/usr/local/etc/dev-containers/meta.env`?
- Could you add a new field to store the Git commit hash?

**Comment by samruddhikhandale** [comment]
@eitsupi A clarifying question, are you looking forward to only modify [devcontainer-info](https://github.com/devcontainers/features/blob/main/src/common-utils/bin/devcontainer-info) file and also source env from `/usr/local/etc/dev-containers/meta.env` and append something like 👇 

> if [ ! -z "${GIT_COMMIT_SHA}" ]; then echo && echo "Git commit: ${GIT_COMMIT_SHA}"; fi

OR are you also looking forward to make these changes to the [devcontainer images](https://github.com/devcontainers/images) & to the [devcontainer-info](https://github.com/devcontainers/features/blob/main/src/common-utils/bin/devcontainer-info) file? 

I believe it's the first one, but would be nice to clarify.

**Comment by eitsupi** [comment]
@samruddhikhandale Thanks for your reply. Sorry for the unclear.

Your first understanding is correct.

I am considering incorporating `meta.env` into images built from https://github.com/rocker-org/devcontainer-images.
We do not plan to generate tags or branches for every build, so I want to show the commit hash as revision. (Using the commit hash as a revision is the same as [the OCI spec annotation](https://github.com/opencontainers/image-spec/blob/188d3a4e194241cf3412010a6c1073a71d4b0708/annotations.md))

And, I wondered if a new path could be used since the path `/usr/local/etc/vscode-dev-containers/meta.env` seems to be a legacy of the past.

**Comment by samruddhikhandale** [comment]
Thanks for the clarification. 

> And, I wondered if a new path could be used since the path /usr/local/etc/vscode-dev-containers/meta.env seems to be a legacy of the past.

I agree, we should support the new image path. I believe we should also make a switch for `devcontainer images` but definitely not a rush.

> Could you add a new field to store the Git commit hash?

I think we could.

@Chuxel would appreciate your thoughts on the request here 👀

**Comment by eitsupi** [comment]
I have created a PR #359 for now.
I hope you will review it when you have time.
