### ISSUE TITLE
[Java] be more specific with needed base image 

### ISSUE THREAD

**Issue by mgoldschmidt-ds** [devcontainers/features#347]
Hey team, 
lately I experienced two issues with java feature.

Issue base image:
I played around with this java feature and found out that image:...base:alpine is not working with it. I guess teh reason is because install.sh is using apt which is not available/used in Alpine Linux.
Is there any possibility to be more specific about the base images needed for a feature? I did not find any entry in the spec, so I would suggest to describe the dependency in the feature readme for example.

Do you have any suggestions on how to be more specific on this issue?
Thanks in advance Michael

**Comment by samruddhikhandale** [comment]
Hey 👋 

Today a PR was merged which adds this OS info --> https://github.com/devcontainers/features/pull/366
For eg. Java now has more details for OS support - https://github.com/devcontainers/features/tree/main/src/java#os-support

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/features/pull/366

**Comment by mgoldschmidt-ds** [comment]
Perfect. Thank you very much!
