### ISSUE TITLE
[Java] be more specific with supported JDKs

### ISSUE THREAD

**Issue by mgoldschmidt-ds** [devcontainers/features#348]
Hey team, 

sdkman.io supports more Java SDK than listed in https://github.com/devcontainers/features/blob/main/src/java/devcontainer-feature.json#L20
I tried it out and it works like a charm even without any changes. 

But to be more specific devcontainer-feature.json we could 
1. either update the readme, point to sdkman.io for supported JDKs and list all available JDKs in jdkDistro proposals, but having to keep track with sdkman updates
2, or update the readme, point to sdkman.io for supported JDKs and remove all jdkDistro proposals, so we do not need to keep track with sdkman updates

But I am not sure which approach would be the preferred one.

Thanks in advance Michael

**Comment by samruddhikhandale** [comment]
HI @mgoldschmidt-ds 👋 

For Feature options, we usually add the most commonly used values to the `proposals` array.
However, the user can definitely use a `jdkDistro` which is not in the proposed list but available in https://sdkman.io/jdks. The Feature accepts other values as well which are not in `proposals` array and installs the distro correctly.

Currently, in the Java's README file we have pointed to a Notice file which includes a list of the available JDK distros with licensing information --> [here](https://github.com/devcontainers/features/blob/main/src/java/README.md#license).

Wondering if that would be sufficient? @mgoldschmidt-ds  What do you think? 
Also, are you looking forward to a specific distro to be listed in that proposed array?

**Comment by mgoldschmidt-ds** [comment]
@samruddhikhandale thanks for clarification. You are right.
For a newbie like me this was not clear in the first place. But with your details it makes sense.
1. I have not read the  the Notice file completely thus I did not find the relation to the jdkDistro options (stopped to read right after the M$ part, my fault). 
2. "usually add the most commonly used values" that was not clear for me the first time I read the readme. But well, "proposal" is just a proposal ;)

After reconsideration: more details would not help, I guess. 
Thanks for your time!
Best regards Michael
