### ISSUE TITLE
The github-cli feature does not work with non-debian based images.

### ISSUE THREAD

**Issue by aetos382** [devcontainers/features#360]
Since `bash` or `apt-get` is used in `install.sh`, it will not work on distributions that do not have these commands.
I would like to have this clearly stated in the documentation.

https://github.com/devcontainers/features/blob/b9bfe406d211ce5645a165a73b72048e9ea9e88e/src/github-cli/install.sh#L1
https://github.com/devcontainers/features/blob/b9bfe406d211ce5645a165a73b72048e9ea9e88e/src/github-cli/install.sh#L63-L69

**Comment by joshspicer** [comment]
Thanks for pointing this out. A note about this used to be in the repo's README, but was removed recently. I'll add a comment to each individual Feature's README expressing its compatibility.

---

With the exception of the `common-utils` Feature, all Features in this repo target debian-based distros. That said, Features themselves can be written to target any linux distribution.  

The reason this repo targets mostly debian distros it to keep maintainability simple for our team.  We encourage others to [write their own Features](https://github.com/devcontainers/feature-starter) if they identify a gap in what's offered in this repo.
