### ISSUE TITLE
Change run order of features?

### ISSUE THREAD

**Issue by gamecss** [devcontainers/features#361]
I'm setuping codespace with a very old ubuntu (13.04).
As we know, apt source of ubuntu older than 14.04 was moved to oldrelease. So if we had a ghcr.io/devcontainers/features/sshd, apt update will fail.
So I wrote a [feature](https://github.com/gamecss/features/tree/main/src/change-ubuntu-oldrelease-aptsource) to modify source.list first.
I wrote .devcontainer.json like this:
```json
{
     "image": "ubuntu:raring",
      "features": {
         "ghcr.io/gamecss/features/change-ubuntu-oldrelease-aptsource:1": {},
         "ghcr.io/devcontainers/features/sshd:1": {
             "version": "latest"
         }
      }
 }
```
But in my test, devcontainers/features/sshd run first and failed because apt fails.
How can I set, or change order to features?

**Comment by gamecss** [comment]
I'm sorry for possible wrong place of issue.

**Comment by joshspicer** [comment]
Hey @gamecss, by default the CLI attempts to intelligently order installation (and we aim to improve that over time).  

If you _need_ to override the install order, there is the `overrideFeatureInstallOrder` property in the `devcontainer.json`.

See: https://containers.dev/implementors/json_reference/
