### ISSUE TITLE
Switching to 16 core codespaces machine type results in loss of docker daemon

### ISSUE THREAD

**Issue by nick-youngblut** [devcontainers/features#374]
If is use a 2 or 4 core codespaces machine type, docker works correctly (e.g., `docker image ls`), but if I change the container to the `16 core, 32 Gb RAM, 128 Gb storage` option, then I get the following error when trying to run docker:

```bash
$ docker image ls
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

If I try to start the docker daemon, I get the following:

```bash
$ sudo systemctl start docker
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

I have tried rebuilding the container, and I have attempted this switch form 2 (or 4) core machines to the 16 core machine multiple times. Each time, I get the `docker daemon` error. 

I need docker and a high memory machine for my development needs, so due to this issue, I have to find an alternative for codespaces (e.g., gitpod). 

My `devcontainer.json`:

```
{
    "name": "nfcore",
    "image": "nfcore/gitpod:2.7.1",
    "postCreateCommand": "python -m pip install --upgrade -r requirements-dev.txt -e ../ && pre-commit install --install-hooks",
    "remoteUser": "gitpod",
    "postCreateCommand": "bash .devcontainer/setup.sh",
    // Configure tool-specific properties.
    "customizations": {
        // Configure properties specific to VS Code.
        "vscode": {
            // Set *default* container specific settings.json values on container create.
            "settings": {
                "python.defaultInterpreterPath": "/opt/conda/bin/python",
                "python.linting.enabled": true,
                "python.linting.pylintEnabled": true,
                "python.formatting.autopep8Path": "/opt/conda/bin/autopep8",
                "python.formatting.yapfPath": "/opt/conda/bin/yapf",
                "python.linting.flake8Path": "/opt/conda/bin/flake8",
                "python.linting.pycodestylePath": "/opt/conda/bin/pycodestyle",
                "python.linting.pydocstylePath": "/opt/conda/bin/pydocstyle",
                "python.linting.pylintPath": "/opt/conda/bin/pylint"
            },
            // Add the IDs of extensions you want installed when the container is created.
            "extensions": ["ms-python.python", "ms-python.vscode-pylance", "REditorSupport.r", "EditorConfig.EditorConfig",
                           "codezombiech.gitignore", "Gruntfuggly.todo-tree", "ms-vsliveshare.vsliveshare",
                           "nextflow.nextflow", "redhat.vscode-yaml", "streetsidesoftware.code-spell-checker"]
        }
	},
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
            "version": "latest"
        },
        "ghcr.io/devcontainers/features/aws-cli:1": {
            "version": "latest"
        }
    }
}
```

**Comment by samruddhikhandale** [comment]
Hi @nick-youngblut 👋 

Thanks for reporting. I tried to reproduce with a 16 core machine type with your devconfig mentioned above, however, omitted `postCreateCommand ` as I don't know the file contents. `docker image ls` worked fine for me.

Few things,
1. Do you mind sharing the creating logs of the Codespace?
2. Is this a 100% repro?
3. Can you combine two `postCreateCommand` properties into one? The dev config is only expected to have one.
4. If 2. doesn't help, then do you mind commenting out two `postCreateCommand` properties and try again? I wonder if some command in the scripts are interfering.
5. If nothing of the above helps, I wonder if the `nfcore/gitpod` image might conflict with the core/dfd settings. Mind switching to a base image for testing? `mcr.microsoft.com/devcontainers/base:ubuntu`

**Comment by nick-youngblut** [comment]
Sure, I'll try those suggestions out. Any idea why the issue only occurs with the 16-core machine?

To be clear, you started with a 2-core machine and then changed the type to the 16-core machine, correct? 
I haven't tried just starting with a 16-core machine. Regardless, switching machines (specific 2 or 4 core to 16 core) shouldn't break docker.

**Comment by nick-youngblut** [comment]
I just tested creating a 16-core machine codespace with the `xdevcontainer.json` listed above (same github repo that previous caused issued). Starting directly with the 16-core machine caused no issues with docker (e.g., `docker image ls` worked). 

So, the issue is caused by changing machine types. I don't know how much testing you all are doing in regards to changing codespace machine types, but I've run into multiple issues when change machine types, including:

* the docker issue described in this issue
* my codespace "breaking" (could not successfully restart the codespace) when changing from 16-core to 2-core
* codespaces freezing for long periods of time after switching between machine times (freezing *after* the machine change has supposedly already finished)

**Comment by samruddhikhandale** [comment]
> To be clear, you started with a 2-core machine and then changed the type to the 16-core machine, correct?

I tried this as well, couldn't reproduce the error (however, omitted postCreateCommand as I don't know the file contents).

![image](https://user-images.githubusercontent.com/24955913/210846145-1210d1b4-ee01-4418-9d6a-aca90c03aa16.png)

Is it a 100% repro for you? It's strange to me that changing machine types would have such an effect unless the scripts executed in postCreateCommand are somehow interfering. 

> then do you mind commenting out two postCreateCommand properties and try again? I wonder if some command in the scripts are interfering.

I would recommend testing to see if the results differ with changing machine types. We can then look at your scripts and identify the issue (if any)

As changing Codespaces machine type is too specific issue for the Codespaces product. Do you mind creating a ticket or starting a discussing in [here](https://github.com/community/community/discussions/categories/codespaces) as it will help involve the broader team. Thanks!

**Comment by nick-youngblut** [comment]
Thanks for looking more into the issue. I will test whether the issue is caused by a combination of changing machine types & the postCreateCommand. 

I'll add the issue to the community discussion (great idea!). I first would like to figure out this issue to have one fully documented issue before I state: "I've had problems changing machine types" with not a very clear understanding of what conditions cause those problems.

**Comment by nick-youngblut** [comment]
I can't reproduce the issue. Switching between the 2-core and 16-core machine types takes quite a long time, and connecting to the codespace can result in some error pages with "restart codespace", but eventually, I am able to connect to the codespace, and docker is running correctly.
