### ISSUE TITLE
Terragrunt latest (0.42.8) failing because missing files in Terragrunt repo

### ISSUE THREAD

**Issue by pipoe2h** [devcontainers/features#399]
The Terraform feature with TFGrunt enabled has started to fail because the latest Terragrunt release, 0.42.8, is missing a lot of the files, including the SHA254SUMS and the binary. 

![image](https://user-images.githubusercontent.com/17649319/212294314-4c2ba213-ba41-490a-84a5-0679afc53f31.png)

**Comment by Oblynx** [comment]
Is there any hotfix? Does an older version of the feature pin the terragrunt version?

**Comment by pipoe2h** [comment]
@Oblynx they are looking into this https://github.com/gruntwork-io/terragrunt/issues/2413

You'll find there an interim workaround that I posted.

**Comment by Oblynx** [comment]
An interesting sideffect is that this breaks our CI. We use devcontainers in the CI.

**Comment by pipoe2h** [comment]
Yeah, same here. Forgot to set a specific version for this within the feature in my devcontainer.json. It's what happen when you leave it set to latest 😄

**Comment by Oblynx** [comment]
Thanks for finding the correct versions! :raised_hands:

**Comment by samruddhikhandale** [comment]
Thanks for the information. Closing this issue as https://github.com/gruntwork-io/terragrunt/issues/2413 is completed & the artifacts for latest version exist. 🎉 

![image](https://user-images.githubusercontent.com/24955913/212390915-3cbf1a89-3558-4140-8d42-418ba17ed787.png)
