### ISSUE TITLE
Add option to `settings.json` for `dev.containers.defaultSettings`

### ISSUE THREAD

**Issue by KatlehoJordan** [devcontainers/features#407]
Apologies if this is the wrong repository to post this feature request in, but then I hope someone can point me in a better direction 🤞 .

I recently ran across the ability to add `dev.containers.defaultExtensions` to my `settings.json` file to have specific extensions installed into any new Dev Container I create. I really like this feature.

However, I do not see a similar feature for automatically activating my settings in Dev Containers. I would like to see a `dev.containers.defaultSettings` entry in `settings.json` to enable this.

Thanks in advance to anyone who can point me in the right direction!

**Comment by samruddhikhandale** [comment]
Hi 👋 

I think this is a good issue for https://github.com/microsoft/vscode.

In the meanwhile, have you looked at the [customizations](https://containers.dev/implementors/json_schema/#base-schema) option for devcontainers yet? That would help add settings to individual dev containers.

**Comment by KatlehoJordan** [comment]
Thanks!

I am aware about the customizations, 🙂 . I was hoping for something that I could set up at the user level rather than the container level. I have opened a feature-request issue in the other repo, so thank you for pointing me there!
