### ISSUE TITLE
Hugo `extended: true` does not install extended version

### ISSUE THREAD

**Issue by ElanHasson** [devcontainers/features#411]
```
$ hugo version
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
```

Feature looks like this per docs.
```
		"ghcr.io/devcontainers/features/hugo:1": {
			"version": "latest",
			"extended": true
		},
```

**Comment by ElanHasson** [comment]
Turns out the reason is because I used the Hugo Dev container base image.

**Comment by aadinesarkar** [comment]
@ElanHasson Could you explain how you fixed this? I'm having the same issue.

**Comment by ElanHasson** [comment]
Sure. @aadinesarkar 

I switched to node base image: https://github.com/ElanHasson/throw.nullreference.io/blob/main/.devcontainer/devcontainer.json#L6

Then use Hugo npm package: https://github.com/ElanHasson/throw.nullreference.io/blob/main/package.json#L37


Configured as such: https://github.com/ElanHasson/throw.nullreference.io/blob/main/package.hugo.json

**Comment by aadinesarkar** [comment]
Thanks @ElanHasson!
Is it a bug that causes the need for this workaround? I expected it to work out of the box. I ended up just changing the image to `"image": "klakegg/hugo:0.107.0-ext-ubuntu"`

**Comment by chelproc** [comment]
In my case, it turned out that [the universal image included Hugo's features by default](https://github.com/devcontainers/images/blob/c5a5f24e3dabb4c8d699619bf23d1b88fb317db0/src/universal/.devcontainer/devcontainer.json#L17), which was causing the issue. Switching to the base image resolved the problem.
