### ISSUE TITLE
docker-outside-of-docker error: "The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed"

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/features#423]
In the last day or two I have started to hit this error when installing the `docker-outside-of-docker` feature:

```
------
 > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/docker-outside-of-docker_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#15 1.035 Get:6 https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye/main amd64 Packages [110 kB]
#15 1.073 Err:3 https://dl.yarnpkg.com/debian stable InRelease
#15 1.073   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#15 1.196 Get:7 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
#15 2.868 Get:8 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [216 kB]
#15 2.916 Get:9 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]

#15 4.934 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#15 4.934 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
#15 4.935 ERROR: Feature "Docker (docker-outside-of-docker)" (ghcr.io/devcontainers/features/docker-outside-of-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker for help troubleshooting this error.
------
```

The `devcontainer.json` I'm using is:

```jsonc
{
	"name": "Go",
	"image": "mcr.microsoft.com/devcontainers/go:0-1.17-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/docker-outside-of-docker:1": {}
	}
}
```

NOTE: Changing to the `1.18-bullseye` image version successfully installs the feature

**Comment by stuartleeks** [comment]
Thanks @jkeech. I just tried `docker pull mcr.microsoft.com/devcontainers/go:0-1.17-bullseye` and it did pull a newer image version. However, I re-ran the dev container on my local machine but still get the issue.

I first hit the issue on the `devcontainers/ci` tests running in GitHub actions - I only tried building locally  to repro and test it.

**Comment by jkeech** [comment]
Ah, sorry for the confusion. Looks like the go-1.17 image is out of support and hasn't been republished since August, which explains why it didn't get rebuilt with the new Yarn key. We only publish updates for language/runtime versions that are in active support.

From the Go docs at https://go.dev/doc/devel/release:
>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release.

Go 1.19 was published on August 2, 2022, which is when support for 1.17 was officially dropped. Devcontainers dropped 1.17 and added 1.19 on August 5, 2022: https://github.com/microsoft/vscode-dev-containers/pull/1564

**Comment by stuartleeks** [comment]
ah, ok - makes sense. Thanks!

**Comment by jkeech** [comment]
Closing this as by-design/won't fix since that image is out of support. I would recommend upgrading to a supported version of Go if possible.
