### ISSUE TITLE
Use GitHub Pages for docs?

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers/features#428]
**Disclaimer:** I don't know if this is a good idea. It's OK if this doesn't happen. This is just a suggestion.

Would it be possible to use a static site generator to auto-generate the documentation for these features? Right now I can't find the documentation information about, for example, the Node.js feature without knowing that it's inside the devcontainers/features repo in the src/node directory. Having a GitHub Pages site might improve SEO for these features to make them searchable? Maybe? IDK.

![image](https://user-images.githubusercontent.com/61068799/215287404-37476349-c64d-4a5f-a654-a6253c1bd81e.png)

This might also help avoid the tedious (at least I think it's tedious) auto-generated documentation commits and clutter since you're deploying the generated docs _elsewhere_ instead of _back into your source control_.

![image](https://user-images.githubusercontent.com/61068799/215287532-f5ee05bf-836a-40af-8b0e-c2b89d4bf22a.png)
![image](https://user-images.githubusercontent.com/61068799/215287610-8d4045f1-52f3-4eb4-9aba-a4735a8e3d7f.png)

**Comment by samruddhikhandale** [comment]
@Chuxel  / @bamurtaugh Wondering if you have any thoughts!

**Comment by bamurtaugh** [comment]
Thanks for opening, @jcbhmr, really appreciate the suggestion!

We currently list Features here: https://containers.dev/features, and you could click into any Feature to learn more about it. It seems this is a bit of the best of both worlds, where docs are included in GitHub (where some users may expect them) and also linked on our containers.dev site. 

Let me know if you have thoughts on this, or any ideas on how we might make https://containers.dev/features or other pages more effective.
