### ISSUE TITLE
Consider adding CONTRIBUTING.md?

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers/features#429]
It would be nice to answer and explain the following in a public document like `CONTRIBUTING.md`:

1. Can I propose a new feature to this repo?
2. How do I submit a bug report?
3. What contributions are accepted?
4. Are there any special code organization rules I should know about?
5. What's the commit style (if any)?
6. Where can I suggest additions to `devcontainer-feature.json`?
7. What code formatter (if any) should I use?
8. How do I open a PR?
9. How do I get started testing these features?
10. How do I get started making changes?

These are all good questions that beginner contributors (like me) will inevitably ask. Having an encouraging document with a loose guide for some common things would be beneficial, I think.

I see there is a small "Contributing" section at the bottom of the readme, but I think more elaboration and detail would be good. And there's also the fact that some people won't scroll down to actually read it, but will see an all-caps "CONTRIBUTING.md" file and read that. 🤷‍♂️ It happens.

**Comment by samruddhikhandale** [comment]
Hi @jcbhmr 👋 

Appreciate this idea 💡 Good one!

**Comment by jcbhmr** [comment]
opened #488

**Comment by jcbhmr** [comment]
You might also want to consider adding a `PULL_REQUEST_TEMPLATE.md` or a `.github/PULL_REQUEST_TEMPLATE.md` that has a notice about **not accepting additional features, only bugfixes** to avoid what seems to happen somewhat often. Something like:

```md
<!--
❤️ Thanks for contributing! Remember that this repository does not accept
new features; we only accept bugfixes for our existing features. [1] If
you've created a new feature that you want to share, check out our guide
to publishing your new feature to the community collection index. [2]

[1]: https://...
[2]: https://...
-->
```
