### ISSUE TITLE
Using os-provided with python ignores devcontainer OS?

### ISSUE THREAD

**Issue by pamelafox** [devcontainers/features#430]
My Dockerfile:

```
FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye
```

My devcontainer.json:

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.0/containers/python-3
{
    "name": "Python 3.11",
    "build": {
        "dockerfile": "Dockerfile",
        "context": ".."
    },
    "features": {
        // https://github.com/devcontainers/features/blob/main/src/python/devcontainer-feature.json
        "ghcr.io/devcontainers/features/python:1": {
            "version": "os-provided"
        }
    },
    // Configure tool-specific properties.
    "customizations": {
        // Configure properties specific to VS Code.
        "vscode": {

            // Set *default* container specific settings.json values on container create.
            "settings": { 
                //"python.defaultInterpreterPath": "/usr/local/bin/python",
                "python.linting.enabled": true,
                "python.linting.pylintEnabled": true,
                "python.testing.unittestEnabled": false,
                "python.testing.pytestEnabled": true,
                "workbench.startupEditor": "newUntitledFile"
            }
        }
    },
    
    // Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
    "remoteUser": "vscode"
}
```

When I open the dev container, it uses Python 3.9 and which python reports /usr/local/python/current/bin/python

I expected for it to use Python 3.11 from the base image. Am I misunderstanding the feature?

**Comment by samruddhikhandale** [comment]
Hi 👋 

The Python image already installs then python 3.11 version. As you are adding the Python Feature with `os-provided` option, the CLI adds another python version (3.9 in this case) and sets it as default. @pamelafox Wondering, why are you adding the Python Feature? 

If you simply remove it, then the dev container will have default `3.11` version

**Comment by pamelafox** [comment]
Ah, I see. I had interpreted "os-provided" as "will use the version on the container OS", but it sounds like it means "use the version on the host OS".

That's a good question as to why I'm using it :) I originally saw it in some other folk's samples so I put it in my own, without fully understanding. It looks like it does add some convenient Python extensions/settings (assuming that https://github.com/devcontainers/features/blob/main/src/python/devcontainer-feature.json is part of the feature?), but I can add those manually to devcontainer.json.

It might be worth clarifying that "os-provided" means the Host OS, in case anyone else mis-interprets it?

**Comment by samruddhikhandale** [comment]
> Ah, I see. I had interpreted "os-provided" as "will use the version on the container OS", but it sounds like it means "use the version on the host OS".

Let's say you build with `ubuntu:focal` image, and you use "os-provided", it adds the apt `python3` package. Hence, the version depends on which version the apt feeds contain.

> It looks like it does add some convenient Python extensions/settings (assuming that https://github.com/devcontainers/features/blob/main/src/python/devcontainer-feature.json is part of the feature?), but I can add those manually to devcontainer.json.

Python image adds the Python Feature [here](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/devcontainer.json#L14), hence, all the settings of the Feature is already added to the image with the [CLI metadata change](https://containers.dev/implementors/spec/#metadata). Thus, you won't have to add them explicitly.

> It might be worth clarifying that "os-provided" means the Host OS, in case anyone else mis-interprets it?

We currently don't have a way to add a description to options but that's a good point. 👍
