### ISSUE TITLE
Unsupported  distribution version 'bookworm'

### ISSUE THREAD

**Issue by sukeyisme** [devcontainers/features#436]
docker in docker

**Comment by samruddhikhandale** [comment]
Are you referring to Debian-bookworm? If so, then it is still in testing and we are waiting for an official release to provide support for it.

https://wiki.debian.org/DebianBookworm

**Comment by sukeyisme** [comment]
yes

**Comment by samruddhikhandale** [comment]
We will support `bookworm` once it's officially released. Thanks!
