### ISSUE TITLE
Add Sentinel CLI to Terraform feature

### ISSUE THREAD

**Issue by sdrzazga** [devcontainers/features#437]
Hi.

I have the feature request to add the [Sentinel CLI](https://docs.hashicorp.com/sentinel/intro/getting-started/install) to `Terraform`.
Thanks in advance.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the request. I think Sentinel would be beneficial for the Terraform Feature, and a nice addition to the existing options (like terragrunt, tfsec, tflint and terraform docs)

@sdrzazga Would you be interested in contributing a PR for adding a `installSentinel` [Feature option](https://github.com/devcontainers/features/blob/main/src/terraform/devcontainer-feature.json#L7-L46)? We could set it's default value to `false`.

// cc @devcontainers/maintainers any concerns?

**Comment by sdrzazga** [comment]
Hello @samruddhikhandale .

I would certainly like to contribute to this via a PR. 
However, I need to confirm this with my employer first, so I need a bit of time.

**Comment by sdrzazga** [comment]
Hello @samruddhikhandale .

I heard back and my employer is ok with contributions.
I already started to work on it and hope to provide a PR for this soon.

**Comment by samruddhikhandale** [comment]
Awesome, thank you!

**Comment by sdrzazga** [comment]
Hey @samruddhikhandale .

I finally managed to push it https://github.com/devcontainers/features/pull/452

**Comment by samruddhikhandale** [comment]
Awesome, thanks! Left some minor comments
