### ISSUE TITLE
devcontainers

### ISSUE THREAD

**Issue by Yusufsuryanata1999** [devcontainers/features#445]
{
    "id": "git",
    "version": "1.1.5",
    "name": "Git (from source)",
    "documentationURL": "https://github.com/devcontainers/features/tree/main/src/git",
    "description": "Install an up-to-date version of Git, built from source as needed. Useful for when you want the latest and greatest features. Auto-detects latest stable version and installs needed dependencies.",
    "options": {
        "version": {
            "type": "string",
            "proposals": [
                "latest",
                "os-provided"
            ],
            "default": "os-provided",
            "description": "Select or enter a Git version."
        },
        "ppa": {
            "type": "boolean",
            "default": true,
            "description": "Install from PPA if available"
        }
    },
    "installsAfter": [
        "ghcr.io/devcontainers/features/common-utils"
    ]
}

**Comment by samruddhikhandale** [comment]
Hi @Yusufsuryanata1999,

Would you help me understand the question/issue here? Thanks!
