### ISSUE TITLE
Question regarding feature development

### ISSUE THREAD

**Issue by sdrzazga** [devcontainers/features#456]
Hi.

I'm new to devcontainer features and seek some guidance on development.
There are a few tools that are at least for me important on a daily basis:

- [MongoDB Atlas CLI](https://www.mongodb.com/docs/atlas/cli/stable/)
- [MongoDB Database Tools](https://www.mongodb.com/docs/database-tools/)
- [MongoDB Shell](https://www.mongodb.com/docs/mongodb-shell/install/)
- [JFrog CLI](https://jfrog.com/getcli/)
- [Chezmoi](https://www.chezmoi.io/)

Sure one or the other could be easily injected via `postCreateCommand ` in the `devcontainer.json`.
However, I believe that implementing it as a feature would make more sense and provides certainly more flexibility/control.

This being said, would it make sense to contribute these features here or rather in a separate project following https://github.com/devcontainers/feature-starter ?

Many thanks for considering my request.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the background information! I agree that it is valuable to add these tools to your dev config via Features.

Have you taken a look at https://containers.dev/features? It lists a wide variety of Features contributed and supported by the community. 

> This being said, would it make sense to contribute these features here or rather in a separate project following https://github.com/devcontainers/feature-starter ?

The `devcontainers/features` repo only accepts improvements and bug fixes for the [current set of maintained Features](https://github.com/devcontainers/features/blob/main/src). 

However, we would appreciate if you could add these Features in a separate repository of your control. The [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) repo should help you get started.

Feel free to ask any questions/queries along the way.

**Comment by sdrzazga** [comment]
Hello @samruddhikhandale .

Thank you for the swift response. Yes, I already had a look at https://containers.dev/features but apart from `MongoSH` I did not find an existing feature there.
Anyways, thank you for the hints.
