### ISSUE TITLE
Graceful handling of features source outage

### ISSUE THREAD

**Issue by bpkroth** [devcontainers/features#493]
At the moment `ghcr.io` is experiencing an outage and returning 503 responses for all requests:
https://www.githubstatus.com/incidents/ybnn77s3lyf8

This results in a failure to load a devcontainer *even* when the devcontainer has already been built.

The only option seems to be to comment out the `/* "features": {...} */` definition in the `devcontainer.json` file.

As an alternative, consider more gracefully handling 503 errors as temporary and allow the (existing) devcontainer to launch as before, perhaps issuing a warning that the container may be missing features due to a temporary upstream outage.

**Comment by jkeech** [comment]
@joshspicer this is another situation where we should cache the feature artifacts locally for true offline builds after the first build.

>As an alternative, consider more gracefully handling 503 errors as temporary and allow the (existing) devcontainer to launch as before, perhaps issuing a warning that the container may be missing features due to a temporary upstream outage.

I'd rather not do this, as we want devcontainers to be fairly deterministic, and if a specific feature is requested, it should either be present in the final container or fail the build. But if we have better caching/offline support, it will mitigate the need to do this. The first time you pull in a feature it would need to be online, but once it's cached locally, it can be used offline.

**Comment by joshspicer** [comment]
Agreed, this scenario is an argument for https://github.com/devcontainers/cli/issues/399

**Comment by bpkroth** [comment]
That'd be a fine solution to my mind as well.
The problem, at least as I see it, atm is that when there's such an outage (which granted should be rare) then the only recourse to be able to get working again is to comment out that section.  That could easily be forgotten to revert, which could lead to a new sort of non-determinism.
Really, once the image is built (be it through the cli or via vscode directly), the features should probably only need to be checked again upon rebuild, so caching them locally and checking that instead seems like a fine solution to me.

**Comment by jkeech** [comment]
I don't think we should require repos to check in the downloaded features, but the devcontainer CLI can keep a local cache of downloaded features and prefer that cache if matching feature versions are already downloaded.

When doing a devcontainer build, we should attempt to resolve the latest version of a feature with a fallback to the cache. For instance, if you pin to the latest major version `:1`, we should attempt to resolve the latest `1.x` version of the feature, but if that fails, we should fall back to the latest cached version as long as it satisfies the requested version (e.g. the latest cached `1.x` would be used).
