### ISSUE TITLE
common-utils installs Zsh even if configured not to

### ISSUE THREAD

**Issue by aaronenberg** [devcontainers/features#507]
Here is my config
```json
"ghcr.io/devcontainers/features/common-utils:2": {
    "installZsh": false,
    "installOhMyZsh": false,
    "username": "vscode",
    "uid": "1000",
    "gid": "1000"
}
```
The devcontainer has zsh installed when it is built with this configuration.

**Comment by samruddhikhandale** [comment]
Hi 👋 

I created a dev container with the following configuration 👇 . It works as expected and `zsh` is not installed. 

```jsonc
{
	"image": "golang:1.20.2",
	"features": {
		"ghcr.io/devcontainers/features/common-utils:2": {
			"installZsh": false,
			"installOhMyZsh": false,
			"username": "none"
		}
	}
}

```

> "username": "vscode"

@aaronenberg Looking at your config, are you using one of the [dev container images](https://github.com/devcontainers/images)? 

These images already has `zsh` installed via the `common-utils` Feature (eg. [base:ubuntu](https://github.com/devcontainers/images/blob/main/src/base-ubuntu/.devcontainer/devcontainer.json#L8)). Hence, currently adding the `common-utils` Feature on top of such an image with `"installZsh": false` won't remove `zsh` from the dev container.

Can you paste your dev container configuration if my explanation isn't applicable in your case? thanks!

**Comment by nls-aarndt** [comment]
@aaronenberg which devcontainer image are you referencing?

**Comment by samruddhikhandale** [comment]
> Is there another way to disable some of the features of a devcontainer image?

Unfortunately, currently we don't have a way to disable Features from a published dev container image.
