### ISSUE TITLE
[features/conda] Conda `latest` version is stuck at v4.12.0

### ISSUE THREAD

**Issue by alexander-smolyakov** [devcontainers/features#513]
**Feature name and version**:
- ghcr.io/devcontainers/features/conda:1

**Description**:

When using the `conda` feature with the `version` option set to `latest` installed 4.12.0 version. However, the latest version available at the moment is [23.3.1](https://github.com/conda/conda/releases/tag/23.3.1). 

The leap between versions is related to the conda team changing versioning strategy ([related announcement](https://github.com/conda/conda/releases/tag/22.9.0)).

I have found a similar issue in the conda repo, but there was no response from the conda dev team:
- ContinuumIO/anaconda-issues/issues/13142

So it seems new versions are unavailable in the `https://repo.anaconda.com/pkgs/misc/debrepo/conda` and related repo used in this feature.

https://github.com/devcontainers/features/blob/f0dd470ba898bb62eb0fa425aa81e86072454167/src/conda/install.sh#L90-L92

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting this, very helpful!

**Comment by alexander-smolyakov** [comment]
_Quick update_:

The Anaconda repo was updated recently and now contains a recent version of conda - `23.1.0`. I have tested the feature with a simple dev container and a `universal` container. All work fine, and the conda feature installed `conda v23.1.0`. Considering it, no additional changes are required for the conda feature.

_Repo metadata_:

```console
Package: conda
Priority: optional
Section: default
Installed-Size: 205109
Maintainer: distribution_team@anaconda.com
Architecture: amd64
Version: 23.1.0-0
Filename: pool/main/c/conda/conda_23.1.0-0_amd64.deb
Size: 68378958
MD5sum: ce5ac4d8cb055a7027d168347bc3a6e6
SHA1: 23a199c37e5dd594c05fda04779d42c551a46388
SHA256: 056758670f3902abf18f8a751d1a33fd341f35690fe0e5a6722174535957884e
SHA512: 9859c04c39dfa80e263d486d551de6504f31d079c1163a37891bfa216b41bf59b81e86e157c5cb3276b0696e0f5f034314a868c16d85007607c09b7bcee585a4
Description: OS-agnostic, system-level binary package manager and ecosystem
Homepage: https://www.anaconda.com
License: BSD 3-Clause
Vendor: Anaconda, Inc

Package: conda
Priority: extra
Section: default
Installed-Size: 193598
Maintainer: distribution_team@anaconda.com
Architecture: amd64
Version: 4.12.0-0
Filename: pool/main/c/conda/conda_4.12.0-0_amd64.deb
Size: 65168050
MD5sum: 4a6b6083310f465638cae6d1b342470e
SHA1: 177a200ec4513c60a17e675f20f4a8462430c83d
SHA256: ba696b8af177f938e857d19319d316c0c28c58f222a86eb024429e3ca8ab9c23
SHA512: e8633a1bf6e52dd7d723d47eaaa9ab5593c09f0e4a69447ebb98e7b9e2743bb97b583aec12610065c20ca28915b6d961a563537bcd481ba2265372ada4594323
Description: OS-agnostic, system-level binary package manager and ecosystem
Homepage: https://www.anaconda.com
License: BSD 3-Clause
Vendor: Anaconda, Inc
```
