### ISSUE TITLE
GPG key error

### ISSUE THREAD

**Issue by akhildevelops** [devcontainers/features#524]
With the below settings. I'm getting GPG key errors.
``` json
"ghcr.io/devcontainers/features/python:1": {
                        "installTools": false,
                        "installJupyterlab": true,
                        "version": "latest"
                }
```

**Comment by dpitkin-bump** [comment]
I'm getting these GPG errors in our CICD, they continue for tflint and terragrunt

[2023-04-19T20:21:21.535Z] #22 0.486 TERRAFORM_VERSION=1.4.5
  
  
  [2023-04-19T20:21:21.686Z] #22 0.643 TFLINT_VERSION=0.46.0
  
  
  [2023-04-19T20:21:21.987Z] #22 0.987 TERRAGRUNT_VERSION=0.45.4
  #22 0.988 Downloading terraform...
  
  
  [2023-04-19T20:21:22.438Z] #22 1.404 (*) Downloading GPG key...
  
  
  [2023-04-19T20:21:23.490Z] #22 2.493 gpg: Signature made Wed Apr 12 17:34:51 2023 UTC
  #22 2.494 gpg:                using RSA key 374EC75B485913604A831CC7C820C6D5CD27AB87
  #22 2.495 gpg: Good signature from "HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>" [unknown]
  #22 2.496 gpg: WARNING: This key is not certified with a trusted signature!
  #22 2.496 gpg:          There is no indication that the signature belongs to the owner.
  #22 2.496 Primary key fingerprint: C874 011F 0AB4 0511 0D02  1055 3436 5D94 72D7 468F
  #22 2.496      Subkey fingerprint: 374E C75B 4859 1360 4A83  1CC7 C820 C6D5 CD27 AB87
  
  
  [2023-04-19T20:21:23.641Z] #22 2.635 terraform_1.4.5_linux_amd64.zip: OK
  #22 2.638 Archive:  terraform_1.4.5_linux_amd64.zip
  #22 2.638   inflating: terraform

**Comment by dpitkin-bump** [comment]
Ran it a 4th time and everything installed okay, no errors

**Comment by samruddhikhandale** [comment]
@akhildevelops has the errors resolved for you as well? Looks like a temporary glitch, I couldn't reproduce the issue.

Let us know if you see such errors again, thanks!

**Comment by akhildevelops** [comment]
It's solved! Thanks
