### ISSUE TITLE
common-utils: Add ~/.config directory for user

### ISSUE THREAD

**Issue by Clockwork-Muse** [devcontainers/features#529]
It can be common to mount (usually, subdirectories of) the user `~/.config` directory, either to persist the configs or to share them between containers.  Unfortunately, if the directory doesn't exist inside the container, mounting it causes it to be owned by root.  This interferes with mundane things like writing the run-once notice at the end of the script, but can cause additional subtler effects.

I'd be willing to make the changes for this, just wanting feedback, especially around whether there are any distro-specific issues here.

**Comment by samruddhikhandale** [comment]
@Chuxel would appreciate your wisdom here, thanks! 🪄 ✨

**Comment by Chuxel** [comment]
Seems like a reasonable request. All that has to be done is the folder is created and owned by the non-root user. At that point the mount point will pick up the privs automatically.
