### ISSUE TITLE
Python: GPG ignores http_proxy environment variable

### ISSUE THREAD

**Issue by tweelix** [devcontainers/features#530]
Hello, I'm trying to use this feature behind a corporate proxy. I can set the **http_proxy** and **https_proxy** environment variables in a custom dockerfile before the features are installed, as well as the apt proxy configs, but sadly gpg ignores those variables by default it seems, and its used for verifying the python source code in the feature.

Conditionally adding `http_proxy="${http_proxy}"` to the `--keyserver-args` fixes the issue.

I could raise a PR for this as I've got it working locally but am unsure how I'd test something like this without spinning up some fake proxy server and seeing if it gets used.

**Comment by samruddhikhandale** [comment]
Hi 👋 

We recently had a community member open a similar PR https://github.com/devcontainers/features/pull/451 for the terraform Feature. 

@tweelix Would something like that help for the python Feature? If so, then feel free to open a similar PR - I can help review, thanks!

**Comment by faltenberg-nex** [comment]
Does anything need to happen to autogenerate the docs for the Readme?

**Comment by tweelix** [comment]
Does anything need to happen to autogenerate the readme with the new parameter?

**Comment by samruddhikhandale** [comment]
We'd need to merge https://github.com/devcontainers/features/pull/542/files ; I'll do that, thanks!
