### ISSUE TITLE
rename all options to be `camelCase` and not `snake_case`

### ISSUE THREAD

**Issue by joshspicer** [devcontainers/features#55]
To follow with JSON naming conventions, we should make all the options in the `devcontainer-features.json` camelCase.

Right now, options are converted to environment variables with [this logic in the CLI](https://github.com/devcontainers/cli/blob/main/src/spec-node/containerFeatures.ts#L25-L28).  

["v2" features]() require environment variables [of this form](https://github.com/devcontainers/features/blob/main/src/docker-in-docker/install.sh#L11-L16), which will get emitted by the tooling.  The tranformation linked above converts what the user types in their `devcontainer-feature.json` to the env variable that is actually emitted by the tooling.

One solution is to sanitize and transform camelcase to CAPITAL_SNAKE_CASE at the capitalization boundaries.

`dockerDashComposeVersion` -> `DOCKER_DASH_COMPOSE_VERSION`.

This change alone would may not automatically be backwards compatible, thus we'll have to be careful with how it is implemented.

**Comment by Chuxel** [comment]
This appears to be fixed, Should we close the issue?

**Comment by joshspicer** [comment]
@samruddhikhandale I think you resolved all these - but please reopen if that's not the case.
