### ISSUE TITLE
[Terraform] tflint update causes builds using terraform feature to fail

### ISSUE THREAD

**Issue by MathBouma** [devcontainers/features#581]
The latest release of tflint (0.47.0) has broken terraform feature.

All devcontainers using terraform latest are failing as a result of a change in tflint.
The container script relies on a checksums.txt.sig file but this wasn't present in the latest release.
I have opened a ticket with tflint:
https://github.com/terraform-linters/tflint/issues/1783

In case the issue needs to be resolved there, but if not a change will be required to this script to workaround this.

**Comment by kf6kjg** [comment]
And they've closed the issues saying the `checksums.txt.sig` was deprecated and now removed, and there's a newer more correct way. Meaning it's now a problem for this project.

**Comment by joshspicer** [comment]
Thanks for raising! I've also run into this, found your closed issue on the tflint project, and eventually made my way back here 😄

Looking into a fix. Thanks @cjam for sharing the workaround!

**Comment by joshspicer** [comment]
Version `1.3.1` of the `terraform` Feature is pinned to tflint `0.46.1` by default (can override with any version you'd like via the Feature's options).  This should unblock folks that are using Feature defaults.

Keeping this issue open while a forward fix is worked on 👍

**Comment by samruddhikhandale** [comment]
@joshspicer should we close this issue as https://github.com/devcontainers/features/pull/586 is merged?
