### ISSUE TITLE
GCP cli - is this feature missing?

### ISSUE THREAD

**Issue by WilliamBonvini** [devcontainers/features#582]
Hi everyone, I've seen that among the features are present both aws-cli and azure-cli, but there is no gcloud-cli. 
I want to ask if such a feature exists under a different name or needs development.
Thank you in advance.

**Comment by bamurtaugh** [comment]
Thanks for the question @WilliamBonvini! As I believe @joshspicer addressed your question, I'll close this issue, but please let us know if you have further questions.

**Comment by WilliamBonvini** [comment]
yes thank you, it solves my problem indeed :)
