### ISSUE TITLE
Add azd to devcontainer features

### ISSUE THREAD

**Issue by hemarina** [devcontainers/features#597]
We want to add azd as a devcontainer feature. Open an issue to track in this repro. 
Related to https://github.com/Azure/azure-dev/issues/1095

**Comment by samruddhikhandale** [comment]
Hi 👋 

We appreciate your Feature contribution, however, the `devcontainers/features` repo only accepts improvements and bug fixes for the [current set of maintained Features](https://github.com/devcontainers/features/blob/main/src). 

However, we would appreciate if you could add this Feature in a separate repository of your control. In your case, that could be https://github.com/Azure/azure-dev

Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/feature-starter#adding-features-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too! 
You can find more guidance here  --> https://github.com/devcontainers/feature-starter & https://containers.dev/guide/feature-authoring-best-practices
