### ISSUE TITLE
Add option in common utils feature: install my rc files instead of yours

### ISSUE THREAD

**Issue by naturedamends** [devcontainers/features#615]
I would like to do that. 

Since, the dev container docker files is executed before the features? I don't have it avaliable to `rm ` in `RUN`?

Ovs I can rm it within the dot files install, but it assumes a clean directory

see pr.
https://github.com/devcontainers/features/pull/614

**Comment by samruddhikhandale** [comment]
Thank you, left some review comments in [here](https://github.com/devcontainers/features/pull/614#pullrequestreview-1546595912)
