### ISSUE TITLE
Docker-in-docker: Use v2 as default for docker compose version

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#620]
> Important
> 
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
> 
> Compose V2 is included with all currently supported versions of Docker Desktop. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).
> 
> Docker’s documentation refers to and describes Compose V2 functionality.

> source: 
https://docs.docker.com/compose/install/standalone/

I agree, and I think we should switch the default for `dockerDashComposeVersion` Feature option to `v2`, thanks for pointing that out.

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/features/issues/619#issuecomment-1642480651_

**Comment by samruddhikhandale** [comment]
proposing to switching from using pip to install, to Docker's instructions https://docs.docker.com/compose/install/standalone/ 

 > https://github.com/devcontainers/features/compare/main...jacobwoffenden:devcontainer-features:use-compose-v2

_Originally posted by @jacobwoffenden in https://github.com/devcontainers/features/issues/619#issuecomment-1642512468_

**Comment by samruddhikhandale** [comment]
> https://github.com/devcontainers/features/compare/main...jacobwoffenden:devcontainer-features:use-compose-v2

> >  Thanks @jacobwoffenden, we appreciate all the help. Would you be willing to open the PR on this repo? As we are switching the  `dockerDashComposeVersion`'s default to `v2`, we'd need to bump the major version of the Feature. Hence, we need to be careful with the migration process as it's a breaking change.

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/features/issues/619#issuecomment-1642554643_

**Comment by dslatkin** [comment]
Does #873 also close this issue?

**Comment by samruddhikhandale** [comment]
Yep, closing as fixed with https://github.com/devcontainers/features/pull/873
