### ISSUE TITLE
Custom .zshrc

### ISSUE THREAD

**Issue by j2udev** [devcontainers/features#623]
I was looking to use the [common-utils](https://github.com/devcontainers/features/tree/main/src/common-utils) feature to setup zsh/ohmyzsh and noticed that there doesn't seem to be a way to use a custom .zshrc?  My Dockerfile is copying it into the remote user's home directory, but it gets overwritten.  The [install script for ohmyzsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh#L333-L336) has a block to account for existing .zshrc files (if the --keep-zshrc flag is set), but it doesn't appear to have made it into the [common-utils feature](https://github.com/devcontainers/features/blob/main/src/common-utils/main.sh#L458)

This is pretty important for doing any sort of customization

**Comment by bamurtaugh** [comment]
Thanks for opening! @joshspicer @samruddhikhandale would be great to get your insights here.

**Comment by samruddhikhandale** [comment]
Hi 👋 

We have https://github.com/devcontainers/features/pull/614 open which proposes to add a new Feature option (`installOhMyZshConfig`) to control the config (ie zsh rc files). Unless I have misunderstood the ask here, @j2udev would `installOhMyZshConfig:false` help, once available?  

Feel free to add your thoughts on the PR.

**Comment by naturedamends** [comment]
In the meantime, you can add your dotfiles (folder or repository) via Dockerfile, via the dev-container dotfiles repository config option, via the mounts dev-container config option,  or via a volume in the `docker-compose.yaml` as seen in the config below. 

Then in the postInstallCommand you can rm the existing file: here is one of my devcontainer.json(s)

```json
{
	"name": "Python 3",

	"dockerComposeFile": [
		"docker-compose.yml"
	],
	"service": "development",

	"workspaceFolder": "/workspace",

	"customizations": {
		"vscode": {
			"settings": {
				"terminal.integrated.shell.*": "/usr/bin/zsh"
			},
			"extensions": [
				"firsttris.vscode-jest-runner",
				"esbenp.prettier-vscode"
			]
		}
	},
	
  "postCreateCommand": "mv /home/vscode/.zshrc /home/vscode/.zshrc.code; DOTFILES_STARTUP=\"/home/vscode/repos/dotfiles/machines/env/empty/\" DOTFILES_DOTFILES=\"/home/vscode/repos/dotfiles\" DOTFILES_ENV=\"empty\" bash -i /home/vscode/repos/dotfiles/machines/env/install.sh ",
	"mounts": [
		"source=/Users/dev/repos/dotfiles,target=/home/vscode/repos/dotfiles/,type=bind",
		"source=/Users/dev/repos/keys/hosts.yml,target=/home/vscode/.config/gh/hosts.yml,type=bind"
	],
	"remoteUser": "vscode",
	"features": {
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/devcontainers/features/common-utils:2": {},
		"ghcr.io/devcontainers-contrib/features/tmux-apt-get:1": {}
	}
}
```
```yaml
version: '3.4'
services:
  development:
    image: "mcr.microsoft.com/devcontainers/python:1-3.11-bullseye"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
```

**Comment by j2udev** [comment]
@samruddhikhandale 
Looking at the PR, yep that should work.
@naturedamends 
Appreciate the PR and suggested workarounds.  In my case, I'm building a devcontainer image in which I'd like my team's custom zshrc baked into the image itself, as opposed to being mounted or installed in a postXCommand. I don't want to impose my personal dotfiles upon my colleagues either, but I've been meaning to give that a go for personal use.

**Comment by naturedamends** [comment]
> @samruddhikhandale
> Looking at the PR, yep that should work.
> @naturedamends
> Appreciate the PR and suggested workarounds. In my case, I'm building a devcontainer image in which I'd like my team's custom zshrc baked into the image itself, as opposed to being mounted or installed in a postXCommand. I don't want to impose my personal dotfiles upon my colleagues either, but I've been meaning to give that a go for personal use.

I too have use for having the dotfiles baked into the container, although I recommend having your main `.zshrc` being a real file (such that programs can append to it without being a change within a repository), that sources your user configuration.

**Comment by naturedamends** [comment]
@samruddhikhandale @j2udev 

Is this possible ?

'''gherkin
Feature
Allow features to declare host file system to dev container image copies.

Given published feature repo
And feature includes metadata for copying host src path to image dest path
When devcontainer build is invoked on target
And target references feature
Then path is COPYed to dev container final image
'''

**Comment by j2udev** [comment]
I see the aforementioned PR was merged so going to close this issue.
