### ISSUE TITLE
common-utils doesn't handle custom $HOME locations

### ISSUE THREAD

**Issue by yangm97** [devcontainers/features#639]
The script expects `HOME=/home/$username`:

https://github.com/devcontainers/features/blob/685fa2e0f151b4545b444135a5ef6877de20e851/src/common-utils/main.sh#L385

But some docker images set the user home directory to somewhere else i.e.

https://github.com/siemens/kas/blob/a560dde924a9e6bdbdd74b901d71a450bec44646/Dockerfile#L59

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for raising this issue, I agree that the `common-utils` Feature should consider this scenario 👍 

We appreciate community contributions, @yangm97 wondering if you'd be interested in contributing a fix for this?
