### ISSUE TITLE
install feature common-utils failed on centOS7

### ISSUE THREAD

**Issue by t2wei** [devcontainers/features#643]
Docker file:
```Dockerfile
ARG platform=aarch64
FROM quay.io/pypa/manylinux2014_${platform}:latest AS data-service
RUN yum install libffi-devel -y \
    && /usr/local/bin/python3.7 -m pip install --upgrade pip \
    && echo "y" | rm /usr/bin/python \
    && ln -s /usr/local/bin/python3.7 /usr/bin/python \
    && ln -s /opt/python/cp37-cp37m/bin/pip /usr/bin/pip 
```
devcontainer.json:
```json
{
  "name": "data-service-dev-vscode",
  "build": {
    "dockerfile": "Dockerfile"
   }
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python",
        "ms-python.vscode-pylance"
      ]
    }
  },
  "features": {
    "ghcr.io/devcontainers/features/common-utils:2": {
      "configureZshAsDefaultShell": true
    }
  }
}
```
Error: No package jq available. Error: Not tolerating missing names on install, stopping.
Please see https://www.cyberithub.com/how-to-install-jq-json-processor-on-rhel-centos-7-8/

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting the issue, I am able to reproduce as well. The `common-utils` Feature was working well with centos OS 7 (like 19 hours ago, see [here](https://github.com/devcontainers/features/actions/runs/5790698488/job/15694249322#step:4:16926)). We have [this scenario](https://github.com/devcontainers/features/blob/main/test/common-utils/scenarios.json#L37-L43) which validates it.

However, looks like something changed (in the upstream) which is now making the `jq` installation fail without the EPEL Repository. 

Meanwhile the `common-utils` Feature is fixed, @t2wei can you add the following statement 👇  to your Dockerfile? It should help you get unblocked. Thanks! 

```
RUN yum install epel-release -y && \
    yum update -y
```

**Comment by samruddhikhandale** [comment]
> The common-utils Feature was working well with centos OS 7 (like 19 hours ago, see [here](https://github.com/devcontainers/features/actions/runs/5790698488/job/15694249322#step:4:16926))

Mmm, never mind I still see 👇 https://github.com/devcontainers/features/actions/runs/5790698488/job/15694249322#step:4:5786. However, it's strange to see the Feature proceeding even with that error in the action run. Looking 👀 

> [2023-08-07T23:06:24.139Z] #15 11.88 No package jq available.

**Comment by samruddhikhandale** [comment]
Opened https://github.com/devcontainers/features/pull/644 with the fix!
