### ISSUE TITLE
ci: Remove `ubuntu:bionic` from the test matrix?

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/features#675]
Given that Ubuntu 18.04 is already EOL (devcontainers/images#90), isn't there a need to test all features on this base image?

https://github.com/devcontainers/features/blob/0668db5edea56a0d57575db127b793f59b489e7b/.github/workflows/test-all.yaml#L43-L52

**Comment by samruddhikhandale** [comment]
Good point, we should remove the deprecated/EOL images from the test matrix 👍 
@eitsupi Feel free to open a PR, if you are interested, thanks!
