### ISSUE TITLE
Make terragrunt optional install in terraform feature

### ISSUE THREAD

**Issue by sethbacon** [devcontainers/features#690]
Not everyone uses terragrunt. Can we please have this be an optional install. I love everything else in the feature, but this one item makes the feature unusable for me.

**Comment by samruddhikhandale** [comment]
Hi 👋 

@sethbacon  Have you tried the following dev config, it should avoid installing `terragrunt` by default. See 👇 

```jsonc
	"features": {
		"ghcr.io/devcontainers/features/terraform:1": {
			"terragrunt": "none"
		}
	}
```

**Comment by sethbacon** [comment]
this works, thanks
