### ISSUE TITLE
PAT is not configured for update-dotnet-install-script workflow

### ISSUE THREAD

**Issue by sliekens** [devcontainers/features#691]
Hello,

The workflow to update the dotnet-install vendor script is missing the access token needed to create a pull request (`secrets.PAT`):
https://github.com/devcontainers/features/actions/runs/6210330803/job/16858424914

It might be the case that the PAT was configured for the `documentation` environment, but I removed this line from the update-dotnet workflow:

``` yml
    environment: documentation
```

@samruddhikhandale what do you think?

**Comment by samruddhikhandale** [comment]
Yes, that's correct. We would need to add the `environment` property, using `documentation` should be fine for now.
