### ISSUE TITLE
Node feature does not pick up proxy settings

### ISSUE THREAD

**Issue by jmedelmann** [devcontainers/features#702]
The [install.sh](https://github.com/devcontainers/features/blob/main/src/node/install.sh) script for the node feature uses npm to install pnpm (Line 231: `npm install -g pnpm`).
Because npm does not pickup the proxy environmentals `http_proxy`, `https_proxy` and `no_proxy` (which are automatically propagated by docker when present in the `~/.docker/config.json` configuration as `httpProxy`, `httpsProxy` and `noProxy`) by itself, the script will always fail behind a proxy.
This is a bug in the install script because this is a special situation not automatically handled by Visual Studio Code or Docker but which must be taken care of by the calling script.

Could you please fix this as follows (bash-compatible)?
```bash
[ ! -z "$http_proxy" ] && npm set proxy="$http_proxy"
[ ! -z "$https_proxy" ] && npm set https-proxy="$https_proxy"
[ ! -z "$no_proxy" ] && npm set noproxy="$no_proxy"
npm install -g pnpm
```

**Comment by momohnasirumuri** [comment]
Run

**Comment by bamurtaugh** [comment]
@samruddhikhandale I'd love to get your thoughts on this one!

**Comment by samruddhikhandale** [comment]
The request makes sense to me. Wondering, @jmedelmann would you be interested in contributing a PR with this change? We'd really appreciate it, thanks!

We could use https://github.com/devcontainers/features/pull/451 as reference, which adds a new "httpProxy" Feature option for the Terraform Feature. It uses the proxy which is either set by the Feature option or if one exists in the env variables.

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/features/pull/712
