### ISSUE TITLE
Would it be possible to add a GDAL feature ? 

### ISSUE THREAD

**Issue by 12rambau** [devcontainers/features#714]
I'm using codespace to performe some remote sensing analysis. The manipulated data are all geospatial and as such dealing with requires [GDAL - Geospatial Data Abstraction Library](https://github.com/OSGeo/gdal#gdal---geospatial-data-abstraction-library). It's the base requirements for all the top Python geospatial libs such as pyogrio, geopandas, fiona, rasterio ... etc

Currently it's impossible to install any of them unless going through the whole installation process. 

Would it be possible to create a feature dealing with GDAL ? or even an OSGEO one like in [heroku ](https://elements.heroku.com/buildpacks/heroku/heroku-geo-buildpack)(PROJ + GEOS + GDAL) ?

**Comment by samruddhikhandale** [comment]
Hi 👋 

We appreciate your thoughts and request for a new Feature, however, the `devcontainers/features` repo only accepts improvements and bug fixes for the [current set of maintained Features](https://github.com/devcontainers/features/blob/main/src). Hence, we don't have any plans for adding support for new Features. 

However, we always motivate and appreciate community contributions which has resulted in a wide list of community authored Features. See https://containers.dev/features, @12rambau I see one community contributed Feature for the `heroku` CLI, would that be helpful?

If not, we would appreciate if you could add this Feature to a separate repository of your control. The [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) repo has more guidance on self authoring them. Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/feature-starter#adding-features-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too!

**Comment by 12rambau** [comment]
> @12rambau I see one community contributed Feature for the heroku CLI, would that be helpful?

Absolutely not. the issue I raised is about geospatial environment, heroku was just an example of a place where its effectively available. 

> If not, we would appreciate if you could add this Feature to a separate repository of your control. 

I simply don't have the bandwidth to work on this unfortunately. If anyone wants to take over from here, let me know.
