### ISSUE TITLE
3.12.0 - gpg: Can't check signature: No public key` installing Python feature

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/features#724]
When building a dev container using the Python feature using the `devcontainer.json` below, I get the error `gpg: Can't check signature: No public key`

```json
{
	"name": "dc-python-tmp",
	"image": "mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-22.04",
	"remoteUser": "vscode",
	"features": {
		"ghcr.io/devcontainers/features/python:1": {
			"version": "latest"
		}
	}
}
```

The dev container builds successfully for me if `version` is omitted or set to `3.11` but fails for `latest` and `3.12`

**Comment by samruddhikhandale** [comment]
Thanks for opening the issue, opened https://github.com/devcontainers/features/pull/726 with the fix!

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/features/pull/726 🚀

**Comment by ofsaleem** [comment]
Using `mcr.microsoft.com/devcontainers/base:ubuntu-24.04`
Getting the same error when trying versions `3.12.0`, `3.12.3`, `3.12.10`, `3.12.11`, and `3.13.0`:

```
30.41 (*) Downloading GPG key...
38.26 Downloading Python-3.12.0.tgz.asc...
38.31 gpg: assuming signed data in 'Python-3.12.0.tgz'
38.38 gpg: Signature made Mon Oct  2 12:04:04 2023 UTC
38.38 gpg:                using RSA key 7169605F62C751356D054A26A821E680E5FA6305
38.38 gpg: Can't check signature: No public key
38.38 ERROR: Feature "Python" (ghcr.io/devcontainers/features/python) failed to install!
```

Curiously, when I remove the `version` field and set the pin to `:1` it works, and appears to install `3.12.3`.
