### ISSUE TITLE
Switch to other desktop manager?

### ISSUE THREAD

**Issue by ghost** [devcontainers/features#725]
I don't like Fluxbox because it is too simple. How do I switch to other desktop manager like Xfce, gnome, cinnamon?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Are you referring to the [desktop-lite](https://github.com/devcontainers/features/tree/main/src/desktop-lite) Feature? 

> How do I switch to other desktop manager like Xfce, gnome, cinnamon?

Currently, as the Feature only installs `Fluxbox`, there is no easy way to switch to other desktop manager by using Feature options.

> I tried to replace fluxbox to xfce4 in install.sh script but it still installs fluxbox

Looks like you are trying to locally modify the Feature, that's one solid approach. If the community shows interest, we could also add your changes to the official Feature.

That said, looking at the Feature, if you comment/remove `fluxbox` from `package_list`, then I don't expect it to be still installed. We do have other functions which copies over configs, but those doesn't seem to install it again.

@Yehh22 How are you running the install.sh script? Is it with a local Feature, then is it possible that your Feature is cached? which could explain why your changes are not reflecting. If not, can you provide me a sample repo and log files?
