### ISSUE TITLE
openvpn feature

### ISSUE THREAD

**Issue by davetapley** [devcontainers/features#740]
Thoughts on this?

- https://github.com/codespaces-contrib/codespaces-openvpn/issues/1

**Comment by samruddhikhandale** [comment]
Hi 👋 

We appreciate your thoughts and request for a new Feature, however, the `devcontainers/features` repo only accepts improvements and bug fixes for the [current set of maintained Features](https://github.com/devcontainers/features/blob/main/src). Hence, we don't have any plans for adding support for new Features. 

However, in this case, given that [codespaces-contrib/codespaces-openvpn](https://github.com/codespaces-contrib/codespaces-openvpn/tree/main) is majorly contributed by @Chuxel, not sure if we'd like to add an official support for it. However, it doesn't look like it's be supported or maintained (as the last commit was two years ago)

// cc @bamurtaugh

**Comment by bamurtaugh** [comment]
Thanks for opening this @davetapley!

I agree with @samruddhikhandale's assessment here. @davetapley if you're interested in hosting a new Feature(s) and contributing it to our community index, we certainly welcome it! Info here: https://containers.dev/collections, https://containers.dev/features.
