### ISSUE TITLE
Consistent Hostname Between Docker Build Layers

### ISSUE THREAD

**Issue by gblikas** [devcontainers/features#747]
**Backgroun**
I was adapting a sample from https://github.com/devcontainers/features/tree/main/src/desktop-lite. That is, using the “build” part of the devcontainer.json file, by creating my own `Dockerfile` and using the “install.sh” script as a part of final layer, via `ENTRYPOINT` and `CMD`, 

```Dockerfile 
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18

// other RUN commands

ENV DBUS_SESSION_BUS_ADDRESS="autolaunch:" \
    VNC_RESOLUTION="1440x768x16" \
    VNC_DPI="96" \
    VNC_PORT="5901" \
    NOVNC_PORT="6080" \
    DISPLAY=":1" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US.UTF-8"
ENTRYPOINT ["/usr/local/share/desktop-init.sh"]
CMD ["sleep", "infinity"]

```

**Issue**
However, I noticed an issue with some other software I was installing and activating prior to this build step: my license and software installed with and target a hostname by the name of `buildkitsandbox`, yet runs with a hostname of something along the lines of `codespace-$(git rev-parse --short head)` (idk, some hash). 

This is causing an error with my license activation not working when I’m launching my software. **Is there a way to change my build process to have a consistent hostname?** 

**Additional Context**

It looks like codespaces is doing something with BuildKit, and this is causing a hostname change, however I’m not familiar enough with Docker buildx to really say. Perhaps we can get a change to codespaces for a dynamic solution like specified in this comment, https://github.com/moby/buildkit/issues/1301#issuecomment-569227496

If you want a flexible way, you can pass the hostname via an env, and parses the specific env here.
You should also modify the hosts here:

> https://github.com/moby/buildkit/blob/f7cf4823f71b1a43b9911d4ee11f0eb502b54cc8/executor/oci/hosts.go#L17

**Comment by samruddhikhandale** [comment]
Hi 👋 

>  and using the “install.sh” script as a part of final layer, via ENTRYPOINT and CMD,

We recommend users to make use of the `features` property in the `devcontainer.json` for installing any Features. Also, we don't provide support or any guarantee that using the script directly would work.

Curious, why do you prefer running it via a script instead of using it in `devcontainer.json` ? 

Also, can you try adding the following to your dev container? 👇 This should set the host name of your container to `buildkitsandbox`
 
```
"runArgs": [
		"--hostname", "buildkitsandbox"
],
```

**Comment by gblikas** [comment]
Thanks for the reply @samruddhikhandale . 

> Hi 👋
> 
> > and using the “install.sh” script as a part of final layer, via ENTRYPOINT and CMD,
> 
> We recommend users to make use of the `features` property in the `devcontainer.json` for installing any Features. Also, we don't provide support or any guarantee that using the script directly would work.
> 
> Curious, why do you prefer running it via a script instead of using it in `devcontainer.json` ?

Trying to expand and create some new functionality. I couldn't find any (good) documentation that really talked about how to extend features, or build my own - if you have some resources, I'd appreciate it. 

> 
> Also, can you try adding the following to your dev container? 👇 This should set the host name of your container to `buildkitsandbox`
> 
> ```
> "runArgs": [
> 	"--hostname", "buildkitsandbox"
> ],
> ```

I will give that a shot - is the implication that the running container with have a hostname of "buildkitsandbox"?

**Comment by gblikas** [comment]
@samruddhikhandale Found some resources on how to build features from scratch, but the section addressing them is small... I also since devcontainer Features are "isolated pieces of code", I'm assuming they cannot be extended, so I'd have to create one from scratch, which would require me to use the Dockerfile and `install.sh` script, anyways; am I understanding this correctly?

**Comment by gblikas** [comment]
Solved this issue with a (bad) workaround of 

```Dockerfile
ENTRYPOINT ["/usr/local/share/desktop-init.sh"]
CMD ["/bin/bash", "-c", "/tmp/someothercommand && sleep infinity"]
```

This causes the `desktop-init.sh` script to launch another shell, via `exec`, rather that "sleep" immediately.
