### ISSUE TITLE
[powershell feature] add option to disable extension install

### ISSUE THREAD

**Issue by sinedied** [devcontainers/features#748]
Would it be possible to add an option to the powershell feature so that it install powershell, but without the VS Code extension?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Looks like you are looking for the https://github.com/devcontainers/features/issues/386. We have already started working on supporting it. Thanks for your patience. 

Once released, you should be able to opt out any extension by using `-` prefix as follows: 

```
"customizations": {
	"vscode": {
		"extensions": {
			"-ms-vscode.powershel",
		}
	}
}
```

Closing this, let's use https://github.com/devcontainers/features/issues/386 for tracking
