### ISSUE TITLE
Desktop-lite fails to open

### ISSUE THREAD

**Issue by minystreem56** [devcontainers/features#749]
Hello, I am using desktop lite on github codespaces, it installed successfully and gave me this output:
`You now have a working desktop! Connect to in one of the following ways:

- Forward port 6080 and use a web browser start the noVNC client (recommended)
- Forward port 5901 using VS Code client and connect using a VNC Viewer

In both cases, use the password "vscode" when connecting

(*) Done!`  
I forwarded port 6080 and when to the website but it shows nothing
![image](https://github.com/devcontainers/features/assets/91996030/ca82aeee-25ad-4780-b5a2-a4bd0fe50056)
Did I forget a step?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Can you try with following config? I was able to make it work in a codespace, thanks! 

I believe that there might be a conflict with web ports vs vnc desktop ports in your `devcontainer.json`. Also, if you use the `password` property, you won't need to type in password each time.

```jsonc
{
    "image": "mcr.microsoft.com/devcontainers/base:jammy",
    "features": {
        "ghcr.io/devcontainers/features/desktop-lite": {
            "password": "vscode",
            "webPort": "6080"
        }
    },
    "forwardPorts": [
        6080
    ],
    "portsAttributes": {
        "6080": {
            "label": "Web VNC"
        }
    }
}
```

**Comment by samruddhikhandale** [comment]
![Image](https://github.com/devcontainers/features/assets/24955913/513c53a2-ff71-4dff-860c-4517723894f0)

Feel free to reopen the issue if you are still running into problems. Thanks!

**Comment by minystreem56** [comment]
Hello, my devconatier.json file looks like, this:`
{
    "id": "desktop-lite",
    "version": "1.0.8",
    "name": "Light-weight Desktop",
    "documentationURL": "https://github.com/devcontainers/features/tree/main/src/desktop-lite",
    "description": "Adds a lightweight Fluxbox based desktop to the container that can be accessed using a VNC viewer or the web. GUI-based commands executed from the built-in VS code terminal will open on the desktop automatically.",
    "options": {
        "version": {
            "type": "string",
            "proposals": [
                "latest"
            ],
            "default": "latest",
            "description": "Currently Unused!"
        },
        "noVncVersion": {
            "type": "string",
            "proposals": [
                "1.2.0"
            ],
            "default": "1.2.0",
            "description": "NoVnc Version"
        },
        "password": {
            "type": "string",
            "proposals": [
                "vscode",
                "codespaces",
                "password"
            ],
            "default": "vscode",
            "description": "Enter a password for desktop connections"
        },
        "webPort": {
            "type": "string",
            "proposals": [
                "6080"
            ],
            "default": "6080",
            "description": "Enter a port for the VNC web client"
        },
        "vncPort": {
            "type": "string",
            "proposals": [
                "5901"
            ],
            "default": "5901",
            "description": "Enter a port for the desktop VNC server"
        }
    },
    "init": true,
    "entrypoint": "/usr/local/share/desktop-init.sh",
    "containerEnv": {
        "DISPLAY": ":1"
    },
    "installsAfter": [
        "ghcr.io/devcontainers/features/common-utils"
    ]
}

`
I got it fromt this repo so I dont know what the issue is, where would I put the devconationer config you linked? I tryied it but It kept giving me errors

**Comment by samruddhikhandale** [comment]
Can you point me to a sample repo where I can try to reproduce the issue? If you used the exact dev container from https://github.com/devcontainers/features/issues/749#issuecomment-1810949117, I don't expect there should be any issues.

**Comment by minystreem56** [comment]
https://github.com/minystreem56/LDTK-vm

**Comment by samruddhikhandale** [comment]
https://github.com/minystreem56/LDTK-vm is missing `.devcontainer.json`, @minystreem56 can you add that as well?

Also, why do you have a local copy of the `desktop-lite` Feature, why not use the Feature's property?

**Comment by minystreem56** [comment]
How would I run the devcontainer file to install desktop lite?

**Comment by minystreem56** [comment]
Ok! I added the devcontianer file!

**Comment by samruddhikhandale** [comment]
Created https://github.com/minystreem56/LDTK-vm/pull/1 if that's easier. 

Welcome to using Dev Containers, we are excited to have you! 🎉 
Feel free to look at https://containers.dev/ for more information.

**Comment by minystreem56** [comment]
ok! thank you for your help!
