### ISSUE TITLE
Template just doesn't work

### ISSUE THREAD

**Issue by worthy7** [devcontainers/features#752]
1. Download the template
2. Make a new feature or change the ID of color or hello feature
3. `Blob /tmp/features-output-1699945273175/devcontainer-feature-.......tgz does not exist.`

**Comment by samruddhikhandale** [comment]
Hi 👋 

Are you referring to the [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) template? 

 > Blob /tmp/features-output-1699945273175/devcontainer-feature-.......tgz does not exist.

I am not sure if I understand this repro step, however, the `tgz` would not generate unless you run the `devcontainer features publish` command. Have you looked at https://github.com/devcontainers/feature-starter#publishing?

**Comment by worthy7** [comment]
@samruddhikhandale  Sorry if this is the wrote repo to post the issue, I didn't realize it.

Yes but there is no mention that I need to run that command on that page, or in the page I was coming from https://code.visualstudio.com/blogs/2022/09/15/dev-container-features#_authoring

**Comment by bamurtaugh** [comment]
Thanks for letting us know @worthy7! If you have a moment, would you be willing to open a PR(s) to that readme? Thank you!
