### ISSUE TITLE
kubectl-helm-minikube - Exposing Minikube ingress in Visual Studio Code Port Forward

### ISSUE THREAD

**Issue by danijam** [devcontainers/features#756]
Hey, I'm getting a bit lost (going round and round on google searches) on how to achieve a forwarding outcome. I've successfully got a dev container in my repo that comes up with Minikube (+ingress addon) that I can start and apply a deployment, service and ingress too. My devcontainer.json is approx like the below:
```json
{
	"name": "k8s",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
			"enableNonRootDocker": "true",
			"moby": "true"
		},
		"ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
			"version": "latest",
			"helm": "latest",
			"minikube": "latest"
		}
	}
}
```
The outcome I want is for someone to be able to clone my repo and all they need is `Visual Studio Code`,`WSL` and `Docker` and they can boot the dev container, attach and then apply workloads to the cluster **and from their windows desktop open the browser and access them via their ingresses**.

My understanding on why this isn't working is that the Minikube ingress comes up using the minikube ip. So `kubectl get ingress -o wide` gives me:
```
NAME              CLASS   HOSTS              ADDRESS        PORTS   AGE
example-ingress   nginx   hello-world.info   192.168.58.2   80      121m
```
`192.168.58.2` being the `minikube ip`

Port forwarding in Visual Studio Code appears to be limited to forwarding to `localhost` or `127.0.0.1` not `192.168.58.2`... I know I can run kubectl port-forward but kinda want to avoid scripting that and just have networking already up and running. I don't think Minikube can come up as ports in the dev container can it? How can I achieve this outcome?

**Comment by samruddhikhandale** [comment]
Hi 👋 

We have information on how to make it work on [kubernetes-helm#ingress-and-port-forwarding](https://github.com/devcontainers/templates/tree/main/src/kubernetes-helm#ingress-and-port-forwarding). Let us know if you are still running into issues, thanks! 

We also have a [kubernetes-helm-minikube](https://github.com/devcontainers/templates/tree/main/src/kubernetes-helm-minikube) Template.

**Comment by samruddhikhandale** [comment]
Feel free to reopen if you have more questions, thanks!
