### ISSUE TITLE
When trying to build a container with this image it says it cannot download buildx-v0.12.0.linux-amd64

### ISSUE THREAD

**Issue by woodman231** [devcontainers/features#758]
Hello,

When I try and create a container with this as a feature I get an error stating that it cannot download buildx-v0.12.0.linux-amd64

When I go to 

https://github.com/docker/buildx/

And review their releases that build is sure enough not available for download. They have their 11 version, and at this moment two release candidates for 12 but not the plain old one. Not sure if this feature needs to be updated with those release candidates or v0.11, or what would be best. But I thought you guys should know.

Thanks,
Sean W.

**Comment by samruddhikhandale** [comment]
Hi 👋 

(Apologies  if I am misunderstanding your question)

> When I try and create a container with this as a feature

@woodman231  Can you help me understand which Feature are you talking about?

> When trying to build a container with this image

Same here, can you tell me the image which is having an issue?

Can you provide me a sample `devcontainer.json` (dev container config) where you are facing these issues? Thanks!

**Comment by samruddhikhandale** [comment]
Hello! 👋 

Appreicate you taking the time in reporting the issue.

Were you referring to having trouble with the `docker-in-docker` Feature? I think you were running into the issue reported in https://github.com/devcontainers/features/issues/556.

Closing in favor of https://github.com/devcontainers/features/issues/556. Let's use ^ for tracking updates, thank you!
