### ISSUE TITLE
DevContainer features behind corporate proxy - Unable to build

### ISSUE THREAD

**Issue by leonhead-acer** [devcontainers/features#783]
I'm using DevContainers behind a corporate firewall. With an existing devcontainer.json file with proxy settings applied with Docker Desktop (Windows/WSL2 installed) the following error occurs only when specifying a feature:

````
Resolving Feature dependencies for 'ghcr.io/rocker-org/devcontainer-features/pandoc:1'...
* Processing feature: ghcr.io/rocker-org/devcontainer-features/pandoc:1
Error: connect ECONNREFUSED 20.248.137.52:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
````

When not specifying a feature the error message still appears but doesn't stop the build (it appears to stop when reading feature manifests).

I'm also unable to add new configuration files to a folder. None of these issues occur when not working behind corporate firewall.

I've tried manually setting proxy settings on Docker Desktop, setting environment variables on Windows and WSL2, updating proxy settings on WSL2 but nothing has worked so far. Any help would be appreciated :)

**Comment by leonhead-acer** [comment]
I had thought of setting proxy settings in Docker Desktop after reading this post:
https://github.com/microsoft/vscode-remote-release/issues/6464#issuecomment-1070944930

No I'm building dev containers using devcontainer.json in VS Code. I'll upload a reprex here soon (computer isn't working at the moment)

**Comment by leonhead-acer** [comment]
````
{
	"name": "Ubuntu",
	"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers-contrib/features/apt-packages:1": {}
	}
}
````

**Comment by eljog** [comment]
> I had thought of setting proxy settings in Docker Desktop after reading this post:

I believe that is because that workaround was suggested to address the scenario where docker was not able to connect to external network. The features are pulled by the devcontainers CLI (used by vscode in your case), not the docker itself. That could be the reason why it is not working for you.

> No I'm building dev containers using devcontainer.json in VS Code. 

I see. In that case the repo and the issue you linked(https://github.com/microsoft/vscode-remote-release/issues/6464#issuecomment-1070944930) is the right place to ask this question

**Comment by leonhead-acer** [comment]
I tested the devcontainer cli and same issue occurred so I wonder if it should be raised there as well. Happy to close this issue
