### ISSUE TITLE
[common-utils]Debian bookworm based images may not have the `/etc/apt/sources.list` file exists

### ISSUE THREAD

**Issue by hsxfjames** [devcontainers/features#786]
repro steps:
1. open command palette, create a new devcontainer based on `Node.js & JavaScript`(or any other debian-based image)
2. choose `Additional Options`, choose `20-bookworm`, mark `Common Utilities` feature enabled, choose `Configure Options`, mark `nonFreePackages` enabled
3. wait for devcontainer building up, then you will see an error occured, and its root cause is: `sed: /etc/apt/sources.list: No such file or directory`

The code at [common-utils/main.sh](https://github.com/devcontainers/features/blob/3ea4d6bbd7864bcf7b5a91fdeeb66e4f5a6f46c0/src/common-utils/main.sh#L105) assumes that the apt sources file(`/etc/apt/sources.list`) should have been existed and uses `sed` to modify it. But actually there is no such file, IMHO the default sources file may be `/etc/apt/sources.list.d/debian.sources`.

Currently I don't know why that file doesn't exists, and whether it is an issue of the base image, or the implementation of features. If more information is needed, tell me and I'll paste it soon, but I think the repro steps are enough.

**Comment by eljog** [comment]
Thank you for sharing the details. I am able to reproduce the issue by following the exact steps you have provided. Have you tried other permutations (such as not selecting `nonFreePackages`, or choosing something other than `20-bookworm`)? And does this issue reproduce in all the cases?

**Comment by hsxfjames** [comment]
@eljog Hi, sorry for the late reply. I've moved to another place and only recently decided to yank my computer out.

> Have you tried other permutations (such as not selecting nonFreePackages, or choosing something other than 20-bookworm)

Yes, I usually not select the `nonFreePackages` in fact. Just because I happened to run into this problem while writing a Dockerfile and wanted to know how you solve it, and then find out it has the same problem :) and this problem does not occur lower than `20-bookworm`, it seems like that they make a change to not provide the `sources.list` file but the deb822 style entry.

**Comment by samruddhikhandale** [comment]
This is similar to https://github.com/devcontainers/images/issues/760

From https://github.com/devcontainers/images/issues/760#issuecomment-1753206829 👇 

> The issue is related to the `nonFreePackages` option of the `common-utils` feature. If this option is enabled, the feature tries to update the packages repo in the `sources.list` file and fails since the `sources.list` file doesn't exist. So, the repro sample could be decreased to:
> 
> ```json
> {
>   "name": "DevSample",
>   "image": "mcr.microsoft.com/devcontainers/base:debian",
>   "features": {
>     "ghcr.io/devcontainers/features/common-utils:2": {
>       "nonFreePackages": true
>     }
>   }
> }
> ```
> 
> The current feature implementation relies on the fact that the `sources.list` file exists and contains links to the packages repo. We need to update the `common-utils` feature to handle the case when the `sources.list` file is empty or doesn't exist more gracefully.
> 
> Related code: [common-utils/main.sh](https://github.com/devcontainers/features/blob/4fca96b5e8a4bfc93679098cb19d73c65ce571eb/src/common-utils/main.sh#L104-L120)

Let's close this as duplicate and track the parent issue, thanks! 

@hsxfjames In the meanwhile, setting `"nonFreePackages": false` should unblock you.
