### ISSUE TITLE
Installing conda will bypass corporate proxy leading to build failure

### ISSUE THREAD

**Issue by Superskyyy** [devcontainers/features#806]
Hi, using the anaconda feature has the following line, which looks like it spawns a new shell that the docker env http_proxy settings are not being used any more. As a result the build fails with timeout getting the package. I have to resort to manual installation for this feature.

https://github.com/devcontainers/features/blob/4697d25cc57cb79fd37845147d6f9adb6044b8c4/src/anaconda/install.sh#L100

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting! 

I believe the following change should fix this 👇 

```
su --login -c "export http_proxy=$http_proxy; export https_proxy=$https_proxy; wget -q https://repo.anaconda.com/archive/Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh -O /tmp/anaconda-install.sh"
```

@Superskyyy Let me know what you think, will shortly open a PR with these changes.

**Comment by Superskyyy** [comment]
> Hi 👋
> 
> Thanks for reporting!
> 
> I believe the following change should fix this 👇
> 
> ```
> su --login -c "export http_proxy=$http_proxy && export https_proxy=$https_proxy && wget -q https://repo.anaconda.com/archive/Anaconda3-${CONDA_VERSION}-Linux-x86_64.sh -O /tmp/anaconda-install.sh"
> ```
> 
> @Superskyyy Let me know what you think, will shortly open a PR with these changes.

Sounds great!

**Comment by AmOmrFFVII** [comment]
> Hi, using the anaconda feature has the following line, which looks like it spawns a new shell that the docker env http_proxy settings are not being used any more. As a result the build fails with timeout getting the package. I have to resort to manual installation for this feature.
> 
> https://github.com/devcontainers/features/blob/4697d25cc57cb79fd37845147d6f9adb6044b8c4/src/anaconda/install.sh#L100

@samruddhikhandale
