### ISSUE TITLE
`java` feature does not have `additionalVersions` options documenteded.

### ISSUE THREAD

**Issue by mirzaprangon** [devcontainers/features#816]
There is an option in the java feature, `additionalVersions`, which allows to install additional versions of JDK without setting it as default. The readme of the feature, even the json does not have the option documented. The `sh` file have the option.

It would be very helpful if the readme have all the options supported documented.

Feature link - https://github.com/devcontainers/features/tree/main/src/java
The src/java/install.sh have the option in it.

**Comment by samruddhikhandale** [comment]
Hi 👋 

When we added the `additionalVersions`, it was experimental and used for testing. Hence, we intentionally did not document it and don't have many test cases validating it's usage.

However, looks like it is working fine and can be publicized/documented provided we add more tests and make sure users can switch between java versions installed using `additionalVersions`.

@mirzaprangon Wondering, would you be interested in contributing that change? We appreciate all the support from the community. Thanks!

**Comment by mirzaprangon** [comment]
Sure, that sounds cool. We are using the devcontainer features extensively and would like to contribute back.

**Comment by gauravsaini04** [comment]
Added changes as suggested [here](https://github.com/devcontainers/features/pull/987)

**Comment by samruddhikhandale** [comment]
Closing as completed!
