### ISSUE TITLE
[docker-in-docker] Docker buildx not installed in Codespaces

### ISSUE THREAD

**Issue by sinedied** [devcontainers/features#817]
In my devcontainer, I'm enabling docker-in-docker using this config:
```
    "ghcr.io/devcontainers/features/docker-in-docker:2": {
      "moby": "false",
    },
```

However, when running in GitHub Codespaces, Docker Buildx doesn't seem to be installed as I get this error when trying to run `azd deploy` on an Azure sample repo using containers:
```
azd deploy

Deploying services (azd deploy)

  (x) Failed: Deploying service backend

ERROR: failed building service 'backend': failing invoking action 'build', building container: backend at ../..: building image: exit code: 1, stdout: , stderr: ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

Here's the installed docker version:
```
docker --version
Docker version 25.0.1, build 29cf629
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting this issue, I am able to reproduce this as well.

From the logs, and after adding some debugging statements, I can see that the `docker-in-docker` Feature is installing and saving `buildx` to https://github.com/devcontainers/features/blob/main/src/docker-in-docker/install.sh#L322

However, within the devcontainer/codespace, I don't see the required path available (ie. `/home/vscode/.docker/cli-plugins/docker-buildx`). It appears like the `~/.docker` folder is getting replaced ; which eventually makes the `buildx` unavailable.

![Image](https://github.com/devcontainers/features/assets/24955913/2317516c-94e9-4ee1-9393-d61fc4a96a53)

I'd need to investigate the purpose of sym-linking `/workspaces/.codespaces/.persistedshare/.docker` to `~/.docker` and either update Codespaces or update the `docker-in-docker` Feature.
