### ISSUE TITLE
DooD line 187: err: command not found

### ISSUE THREAD

**Issue by lucasfcnunes** [devcontainers/features#865]
Suddenly, running the `docker-outside-of-docker/install.sh` script gives me the following:

```
docker-outside-of-docker/install.sh: line 187: err: command not found
```

*I'm using the latest file (as of now) https://github.com/devcontainers/features/blob/eea8ec3a3702057ce3c0c3e54bbb205ed580867b/src/docker-outside-of-docker/install.sh

### Info:

- image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
- `docker info`:
```
Client:
 Version:    24.0.9-1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1-1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.5-1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

### May be related with:

- https://github.com/devcontainers/features/pull/843
- https://github.com/devcontainers/features/issues/842

**Comment by samruddhikhandale** [comment]
Left a PR review for https://github.com/devcontainers/features/pull/867

:tldr We don't provide guarantee or support that using scripts would always work.

Can you try updating your dev container to add Feature? See https://github.com/devcontainers/features/blob/main/src/docker-outside-of-docker/README.md#example-usage
