### ISSUE TITLE
check for systemctl symlink in common-utils installing script

### ISSUE THREAD

**Issue by remifan** [devcontainers/features#898]
Issue:

in [src/common-utils/bin/systemctl](https://github.com/devcontainers/features/blob/965e12010f31baea61c7a9389082b19cfe498207/src/common-utils/bin/systemctl#L4), `cp -f "${FEATURE_DIR}/bin/systemctl" /usr/local/bin/systemctl` may fail if there exists a symlink `/usr/local/bin/systemctl` pointing to [some systemd scripts](https://github.com/gdraheim/docker-systemctl-replacement) in custom docker image.

**Comment by samruddhikhandale** [comment]
The `cp -f command in bash will not fail if /usr/local/bin/systemctl `is a symlink. The `-f` option stands for "force" and it will overwrite the target file (or symlink in this case) without asking.

However, if `/usr/local/bin/systemctl` is a symlink to a file within a Docker image and you're running the cp command from the host system, the symlink would likely point to a non-existing file from the host's perspective. The cp command would overwrite the symlink itself, not the file inside the Docker image.

If you want to preserve the symlink and copy the file it points to, you should use the -L option with cp:

```
cp -fL "${FEATURE_DIR}/bin/systemctl" /usr/local/bin/systemctl
```

This will follow the symlink and copy the file it points to. But again, this will only work if the symlink points to a valid file from the perspective of where you're running the cp command.

@remifan Would you be interested in creating a PR with these changes provided it makes sense to yo?
