### ISSUE TITLE
docker-outside-of-docker on ubuntu 23.10

### ISSUE THREAD

**Issue by ivirabyan** [devcontainers/features#905]
Looks like docker-outside-of-docker feature only supports Ubuntu up to 22.04: https://github.com/devcontainers/features/blob/main/src/docker-outside-of-docker/install.sh#L23

Could it support 23.10 (codename `mantic`) as well?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Generally, we actively add support for LTS versions, hence we did not add it for `mantis`. However, @ivirabyan  feel free to contribute a PR with these changes if you are interested.

**Comment by ivirabyan** [comment]
That makes sense, I'll close this one then.
