### ISSUE TITLE
desktop-lite noVNC > 1.2.0 not installing

### ISSUE THREAD

**Issue by s0urce-c0de** [devcontainers/features#910]
with the following file in `.devcontainer/devcontainers.json`:
```jsonc
{
  "features": {
    "ghcr.io/devcontainers/features/desktop-lite:1": {
      "noVncVersion": "1.4.0", // Any version above 1.2.0 not working.
    }
  },
  "forwardPorts": [5901, 6080],
}
```
It forwards the port but no process is running on it.
Any idea how I can fix this?

**EDIT**: There is a process running on 5901

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting. Identified the bug in this [line](https://github.com/devcontainers/features/blob/5ad3f6fbbf63096917622ac3da72266ad377c984/src/desktop-lite/install.sh#L230). 

The URL to download the artifacts have been updated from ` https://github.com/novnc/noVNC/archive/refs/tags/v*` to `https://github.com/novnc/noVNC/archive/refs/tags/v`. Hence, you are running into this issue. We need to fix it and ensure we support installing v1.2.0 along with any other versions. 

Also, updating the Feature to support `latest` version would be helpful.

**Comment by s0urce-c0de** [comment]
I think download URL still works because both `https://github.com/novnc/noVNC/archive/v1.2.0.zip` and `https://github.com/novnc/noVNC/archive/v1.4.0.zip` both give me zip files with the contents. May this be related to the fact that launch.sh is missing in the 1.4.0 release: `https://github.com/novnc/noVNC/tree/90455eef0692d2e35276fd31286114d0955016b0/utils`?

I believe [this](https://github.com/devcontainers/features/blob/main/src/desktop-lite/install.sh#L370) line launches it in `desktop_init.sh` (the entrypoint). 


Also if multiple versions are installed then it picks the earlier version. This happens if you manually run install.sh after modifying the version number, and then running `/usr/local/share/desktop_init.sh`. I think this is due to the glob pattern. May I suggest saving this version number to a file and then reading from it? Or removing `/usr/local/novnc` to install a new version fresh?

**Comment by s0urce-c0de** [comment]
Also I think this command should correctly print the latest version:
```bash
curl -Ls "https://github.com/novnc/noVNC/releases/latest" | sed -n 's/.*<include-fragment loading="lazy" src="https:\/\/github.com\/novnc\/noVNC\/releases\/expanded_assets\/v\([^"]*\)".*/\1/p'
```
**WARNING**: Will also print beta versions

**Comment by s0urce-c0de** [comment]
I think on line 369-370 you need to replace launch.sh with novnc_proxy

**Comment by s0urce-c0de** [comment]
I figured it out
