### ISSUE TITLE
Fix tests: nvidia-cuda (liburcu6)

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/features#941]
> Looking at the test failures, looks like we need to install `liburcu6` based on the distro type. 
> Also, I am seeing similar errors on the `main` branch ([ref](https://github.com/devcontainers/features/actions/runs/8633868409/job/23667938174)). This PR does not impact the test failures, hence, I can track them in another issue. 
> 
> >  looks like we need to install `liburcu6` based on the distro type. 
> 
> Can you help revert the `liburcu6` change or feel free to help us with ^

_Originally posted by @samruddhikhandale in https://github.com/devcontainers/features/pull/933#discussion_r1559685937_

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Can you help fix the tests for nvidia-cuda Feature? Thanks! https://github.com/devcontainers/features/actions/runs/8633868409/job/23667938174

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
I have raised a PR to fix this. 
[PR 942](https://github.com/devcontainers/features/pull/942)
`liburcu6` package was not installable so I have used dpkg to download deb package and install. After the changes, test case is passed.
let me know if any change/improvement is need to fix this.

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,
Updated the PR with the changes suggested. Test cases are passing.
