### ISSUE TITLE
[desktop-lite] Entrypoint script does not use VNC_RESOLUTION defined by containerEnv

### ISSUE THREAD

**Issue by Huoleit** [devcontainers/features#945]
## Summary

As written in the [`desktop-init.sh`](https://github.com/devcontainers/features/blob/e7dd9fafd9aeede11d0a59a0ace819e3b774de2a/src/desktop-lite/install.sh#L293) , the entrypoint script will use user-defined `VNC_RESOLUTION` if provided. But even if I include the env definition in both `containerEnv` and `remoteEnv`, the entrypoint script always uses the default setting. 

## Screenshot
![Screenshot from 2024-04-15 15-10-01](https://github.com/devcontainers/features/assets/29969110/ba334c26-4893-4bfa-a047-b876e27d3d98)

## Steps to reproduce

`.devcontainer` used.
```
{
	"name": "Ubuntu",
	"image": "mcr.microsoft.com/devcontainers/base:jammy",
	"features": {
		"ghcr.io/devcontainers/features/desktop-lite:1": {}
	},
	"containerEnv": {
		"VNC_RESOLUTION": "1920x1080x32"
	},
	"remoteEnv": {
		"VNC_RESOLUTION": "1920x1080x32"
	},
	"forwardPorts": [
		5901,
		6080
	],
	"containerUser": "vscode"
}
```
## Log
```
[2024-04-15T13:06:53.341Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/docker_test,target=/workspaces/docker_test --mount type=volume,src=vscode,dst=/vscode -e VNC_RESOLUTION=1920x1080x32 -u vscode --init --entrypoint /bin/sh vsc-docker_test-07c641cc479b026b86df51ee3bad1935608dd8988b8d00265001f60892599974-features-uid -c echo Container started
```

**Comment by Huoleit** [comment]
After investigating, it appears that `docker run` doesn't pass environment variables to a non-interactive shell. One workaround is setting those variables in the Dockerfile using `ENV`. However, since `VNC_RESOLUTION` is user-specific and I prefer not to expose it in the Dockerfile, is there a better approach to configure it in `devcontainer.json`?

**Comment by samruddhikhandale** [comment]
Ideally, using `containerEnv` to update `VNC_RESOLUTION` in `devcontainer.json` should work out of the box. It's strange that it's not working for you. 

Please note that changes to the `devcontainer.json` file will not take effect in an existing container. You'll need to rebuild the container for the changes to take effect. You can do this by running the "Remote-Containers: Rebuild Container" command in Visual Studio Code.

>  docker run doesn't pass environment variables to a non-interactive shell.

Docker does pass environment variables to non-interactive shells. When you use the -e or --env option with docker run, the environment variables are set for all processes in the container, including non-interactive shells.

> > docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/docker_test,target=/workspaces/docker_test --mount type=volume,src=vscode,dst=/vscode -e VNC_RESOLUTION=1920x1080x32 

From the logs, it looks right to me ^

@gauravsaini04 Can you help investigate this issue? To start with, can you see if you can repro the issue as described by @Huoleit ? Thanks!

**Comment by Huoleit** [comment]
I finally found the issue. Variables defined inside heredocs (see [here](https://github.com/devcontainers/features/blob/bb7b7ea29f84ea31262c1290a2e14e9984286295/src/desktop-lite/install.sh#L293)) are not escaped. Instead, they are evaluated or assigned default values during build time. That is why variables passed by `docker run -e VNC_RESOLUTION` do not work, but defining them in the Dockerfile does.

Inspecting the final entrypoint script also proves my thoughts. They are evaluated during build time.

```bash
#!/bin/bash

user_name="root"
group_name="root"
LOG=/tmp/container-init.log

export DBUS_SESSION_BUS_ADDRESS="autolaunch:"
export DISPLAY=":1"
export VNC_RESOLUTION="1440x768x16" 
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
...
```

**Comment by gauravsaini04** [comment]
Hi,
I could check the value of env var set inside the container to be the same as what's in `.devcontainer.json` file i.e. 1920x1080x32
Got the following output for this command : 

 ```
docker exec 6c32dfa6ec6b10cba6b54379cf9a69e6e97919d89e4a78450e6d7d91f399bf7a bash -c 'echo "$VNC_RESOLUTION"'
1920x1080x32
```

**Comment by Huoleit** [comment]
> Hi, I could check the value of env var set inside the container to be the same as what's in `.devcontainer.json` file i.e. 1920x1080x32 Got the following output for this command :
> 
> ```
> docker exec 6c32dfa6ec6b10cba6b54379cf9a69e6e97919d89e4a78450e6d7d91f399bf7a bash -c 'echo "$VNC_RESOLUTION"'
> 1920x1080x32
> ```

I am not referring to it. Env, of course, works as expected if it is passed to `docker run -e`. Please take a look at `/usr/local/share/desktop-init.sh` inside the container. All variables are substituted because they are not escaped.

```bash
user_name="vscode"
group_name="vscode"
LOG=/tmp/container-init.log

export DBUS_SESSION_BUS_ADDRESS="autolaunch:"
export DISPLAY=":1"
export VNC_RESOLUTION="1440x768x16" 
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
```
Echo `VNC_RESOLUTION` in this case will print the correct user-defined value.
```
# echo $VNC_RESOLUTION                 
1920x1080x32
```

But during the build, the user-defined `VNC_RESOLUTION`  is not passed to `docker build`. `VNC_RESOLUTION` defined inside `/usr/local/share/desktop-init.sh` will always be substituted by the default value 1440x768. When starting the container, it always use the default 1440x768 no matter what is given to `docker run -e`. It can be verified by 

```bash
# ps -x -ww | grep Xtigervnc
110 ?        Ss     0:00 /usr/bin/Xtigervnc :1 -localhost=1 -desktop fluxbox -rfbport 5901 -SecurityTypes None -auth /home/vscode/.Xauthority -geometry 1440x768 -depth 16 -dpi 96
```

**Comment by gauravsaini04** [comment]
Added pr #1024 as a solution to this problem..

**Comment by gauravsaini04** [comment]
PR was merged

**Comment by samruddhikhandale** [comment]
@gauravsaini04 The PR was causing issues as reported in https://github.com/devcontainers/features/issues/1085. Hence, I have reverted your changes.

Can you reopen the issue with the fix for this issue while ensuring desktoplite starts fine post container startup?

**Comment by gauravsaini04** [comment]
Have raised pr #1112

**Comment by gauravsaini04** [comment]
Had raised PR #[1112](https://github.com/devcontainers/features/pull/1112) for it which got merged
