### ISSUE TITLE
How to install a preview version dotnet sdk

### ISSUE THREAD

**Issue by WeihanLi** [devcontainers/features#948]
I want to install a preview dotnet sdk without specific version, for example, I want to install with the latest .NET 9 preview sdk

how could I specify the version? I tried with `9.0.x` but not working

Could we support `preview` to install the latest preview version

**Comment by bamurtaugh** [comment]
@joshspicer is there a way to specify to install the latest preview version, rather than lts?

**Comment by WeihanLi** [comment]
any update?

**Comment by joshspicer** [comment]
Hey there! I tested this morning and the following dev container with the option `version: "9.0"` installs `9.0.100-preview.6.24328.19`.

```json
{
  "image": "mcr.microsoft.com/devcontainers/base",
  "features": {
    "ghcr.io/devcontainers/features/dotnet": {
      "version": "9.0"
    }
  }
}
```



![Image](https://github.com/user-attachments/assets/50f94901-0f89-4588-9118-ed466008de5a)

The [Feature's README](https://github.com/devcontainers/features/tree/main/src/dotnet#options) documents that the `version` option can be of shape `X.Y` or `X.Y.Z`.  

It appears we don't support `9.0.x` not sure if the upstream `dotnet-install.sh` (which we [vendor](https://github.com/devcontainers/features/blob/main/src/dotnet/scripts/fetch-latest-dotnet-install.sh)) script does)
