### ISSUE TITLE
Support specifying PowerShell Module Version

### ISSUE THREAD

**Issue by russellds** [devcontainers/features#963]
It would be extremely helpful if you could specify the version of the PowerShell module(s) to be installed. There are times where I need a specific version, typically with the Azure PowerShell module, because of issues with the latest version.

A simple way to do it would be to seperate the module and version with a colon, see below. If the version is not specified, then install the latest as it currently works.

``` json
"ghcr.io/devcontainers/features/powershell:1": {
      "version": "latest",
      "modules": "powershell-yaml,Az:11.4.0"
    }
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

The request makes sense to me and I like the suggested approach of using the `:` delimiter ; adding this item to the backlog! 

@russellds if you are interested, feel free to open a PR with the proposed changes. We appreciate community contributions and I'm happy to help with the reviews 🙏

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,

I have created the PR for this fix here: https://github.com/devcontainers/features/pull/993
kindly review and approve the same if it satisfies the user requirements

**Comment by prathameshzarkar9** [comment]
Hi @samruddhikhandale ,

Addressed review comments on the PR and also added a test case to verify the specified Powershell module version is installed successfully.
