### ISSUE TITLE
docker-compose.yml not found for "dockerComposeFile": [] 

### ISSUE THREAD

**Issue by parherman** [devcontainers/features#965]
In v0.365.0 (pre-release) docker-compose.yml is no longer found in the workspace when using a empty array with dockerComposeFile

I use an empty array so that I can use docker-compose.override.yml as suggested by this comment [comment](https://github.com/microsoft/vscode-remote-release/issues/1080#issuecomment-824087033) in issue https://github.com/microsoft/vscode-remote-release/issues/1080

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for opening the issue. However, the `devcontainers` team does not maintain the VS Code UX or the `Dev containers` extension.

Can you open an issue in https://github.com/microsoft/vscode-remote-release/issues? The VS Code team should be able to help you provide guidance. Thanks!
