### ISSUE TITLE
docker-in-docker: support noble

### ISSUE THREAD

**Issue by nathanweeks** [devcontainers/features#967]
An Ubuntu 24.04 ("noble") dev container image has been released: https://github.com/devcontainers/images/issues/1016#issuecomment-2103207443

However, the docker-in-docker dev container feature does not currently recognize `noble` as a valid distribution:
https://github.com/devcontainers/features/blob/d8e9d335952d0b8d488cc3445ad076003bc3c22c/src/docker-in-docker/install.sh#L21-L22

Resulting in a failure when the feature's install.sh script is run:
https://github.com/devcontainers/features/blob/d8e9d335952d0b8d488cc3445ad076003bc3c22c/src/docker-in-docker/install.sh#L194-L207

**Comment by jjh42** [comment]
https://github.com/devcontainers/features/pull/969 made a PR to fix this, comment contains by own build of the feature you can use as a temporary workaround.
