### ISSUE TITLE
features/desktop-lite failed to install in ubuntu24.04

### ISSUE THREAD

**Issue by ddosakura** [devcontainers/features#968]
```
8.713 Package libasound2 is a virtual package provided by:
8.713   liboss4-salsa-asound2 4.2-build2020-1ubuntu3
8.713   libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
8.713 
8.717 E: Package 'libasound2' has no installation candidate
```

**Comment by samruddhikhandale** [comment]
Given the recent release of ubuntu24.04, looks like we need to update the `Desktop-lite` Feature for compatibility. 

@gauravsaini04 Can you help fix this? Thanks!

**Comment by gauravsaini04** [comment]
Hi,
Have raised a possible solution as PR [#973](https://github.com/devcontainers/features/pull/973)

**Comment by gauravsaini04** [comment]
The PR raised was merged by @samruddhikhandale. 👍
