### ISSUE TITLE
Fly.io feature not being supported anymore

### ISSUE THREAD

**Issue by GMkonan** [devcontainers/features#972]
The feature to install flyctl in a dev container has an issue with installing the latest version. The workaround for everyone using it right now is specifying the version you wanna use it, so the feature can install the CLI correctly.

This problem can be described in https://github.com/dhoeric/features/issues/25 and https://github.com/dhoeric/features/issues/31. Where I talk about the problem and create a PR (https://github.com/dhoeric/features/pull/26) to fix. But the creator of that repo doesn't seem to maintain it anymore.

I could create a new feature for the fly CLI, but I'm not sure how should I pass it here since it kinda already exists. Can someone guide me in this? Would I create one to substitute it? Or it would have a `deprecated` one and the current one?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Unfortunately, we won't be able to mark the fly CLI as deprecated ; unless the author themselves decides to update & mark it as deprecated.

However, you can add this Feature with the fix in a separate repository of your control. The [devcontainers/feature-starter](https://github.com/devcontainers/feature-starter) repo has more guidance on self authoring them.

Once you've self authored and if you'd like to share it with the community, we'd recommend [adding it to the index](https://github.com/devcontainers/feature-starter#adding-features-to-the-index). It will make them visible in our [supporting tools](https://containers.dev/supporting) (like https://containers.dev/templates, Dev Containers Extension, GitHub Codespaces etc).

Feel free to ask any questions/queries along the way, feedbacks are welcome too!

> I could create a new feature for the fly CLI, but I'm not sure how should I pass it here since it kinda already exists

As it will be hosted in your repository, it will still be unique and users can find your Feature once you add to the index.

**Comment by bamurtaugh** [comment]
Closing as I believe this was addressed by https://github.com/devcontainers/devcontainers.github.io/pull/411!
