### ISSUE TITLE
[azure-cli] missing `noble` in the AZCLI_ARCHIVE_VERSION_CODENAMES

### ISSUE THREAD

**Issue by DariuszPorowski** [devcontainers/features#980]
the `AZCLI_ARCHIVE_VERSION_CODENAMES` does not contain the latest LTS version of Ubuntu 24.04 (noble)
https://github.com/devcontainers/features/blob/main/src/azure-cli/install.sh#L21

packages.microsoft.com already has `noble` release for azure cli: https://packages.microsoft.com/repos/azure-cli/dists/noble/

**Comment by samruddhikhandale** [comment]
@gauravsaini04 Can you help fix this? Thanks!

**Comment by gauravsaini04** [comment]
i have added this [pr](https://github.com/devcontainers/features/pull/986)

**Comment by samruddhikhandale** [comment]
Closing as completed with https://github.com/devcontainers/features/pull/986
