### ISSUE TITLE
docker-outside-of-docker incompatible with Ubuntu 22.04?

### ISSUE THREAD

**Issue by therealmitchconnors** [devcontainers/features#983]
Hi this is Mitch from the Istio team.  We're trying to use codespaces, particularly with the docker-outside-of-docker feature.  Our devcontainers were working fine for a while, but now it appears that the feature fails to build due to some strange Operating System incompatibilities... 
In particular, I'm hitting this line here, which seems to indicate that my operating system is not supported: https://github.com/devcontainers/features/blob/main/src/docker-outside-of-docker/install.sh#L200
features/src/docker-outside-of-docker/install.sh at main · devcontainers/features
A collection of Dev Container Features managed by Dev Container spec maintainers. See https://github.com/devcontainers/feature-starter to publish your own - devcontainers/features
I'm on Ubuntu 22.04, codename jammy (U-22), which appears to be supported, but I can't tell where the VERSION_CODENAME variable is populated...
Also, I'm not getting a helpful error message, because bash is complaining that the 'err' command is not found... I'm not sure what's up with that, but it's not the core problem.  It's just obfuscating the error message.

**Comment by samruddhikhandale** [comment]
Hi 👋 

I was able to create a codespace with the following `.devcontainer.json` 👇 

![Image](https://github.com/devcontainers/features/assets/24955913/eebeccd6-09f4-4282-bc1f-8ce85117491a)

@therealmitchconnors  Can you help answer following questions?

- What version of Feature are you using? ( Make sure your lockfiles are updated if needed)
- Can you share a minimum copy of dev config for repro?
- Can you share codespace creation logs?

**Comment by therealmitchconnors** [comment]
This behavior disappeared when I tried running the container in another environment.  It must be something on my side.  Thanks for validating the baseline behavior!
